package com.training.client.constants;

public enum ClientConstant {
	TAGS_SEO ("seoTags"),
	MODULE_NAME_TO_DISPLAY ("moduleName"),
	
	RESPONSE_STATUS ("status"),
	RESPONSE_MESSAGE ("message"),
	RESPONSE_CODE ("statusCode"),
	CLASS_SUCCESS ("success-color"),
	CLASS_ERROR ("danger-color"),
	CLASS_NAME ("errorClass"),
	HTML_MESSAGE_KEY ("htmlMessage"),
	
	RESPONSE_STATUS_SUCCESS ("1"),
	RESPONSE_STATUS_FAILURE ("0"),
	RESPONSE_STATUS_ERROR ("2"),
	
	//PAGE SHOULD BE IN CONSTANTS
	PAGE_COMMON_RESPONSE ("common/CommonResponse"),
	PAGE_LOGIN ("Login"),
	PAGE_SIGNUP ("SignupCommon"),
	PAGE_SIGNUP_LOGIN ("CommonLanding"),
	PAGE_RESET_PASSWORD("ChangePassword"),
	PAGE_ENQUIRY("Inquiry"),
	PAGE_ENQUIRY_THANKYOU("InquiryThankyou"),
	
	MODULE_NAME_COMMON("COMMON"),
	MODULE_NAME_ADMIN("ADMIN"),
	MODULE_NAME_STUDENT("STUDENT"),
	MODULE_NAME_TEACHER("TEACHER"),
	MODULE_NAME_SCHOOL("SCHOOL"),
	MODULE_NAME_PARENT("PARENT"),
	MODULE_NAME_AUDITOR("AUDITOR"),
	
	MODULE_EVENT_REGISTRATION ("Registration"),
	MODULE_EVENT_LOGIN ("Login"),
	MODULE_CHANGEPASS_LOGIN ("Change Password"),
	MODULE_EVENT_DASHBOARD ("Dashboard"),
	MODULE_NAME_SIGNUP_STUDENT ("Student"),
	MODULE_NAME_SIGNUP_VOCAIONAL_STUDENT ("Vocational Course"),
	MODULE_NAME_SIGNUP_FLEXCOURSE_STUDENT ("Flex Program"),
	MODULE_NAME_SIGNUP_SCHOOL ("School"),
	MODULE_NAME_SIGNUP_SCHOOL_B2B ("School"),
	MODULE_NAME_SIGNUP_TEACHER ("Teacher"),
	MODULE_EVENT_ENQUIRY ("Inquiry"),
	MODULE_EVENT_PPC ("PPCRequest"),
	MODULE_EVENT_REQUEST_A_DEMO ("RequestADemo"),
	MODULE_EVENT_ENQUIRY_REPLY ("Inquiry Reply"),
	
	PAGE_DASHBOARD_COMMON ("/Dashboard"),
	AJAX_PAGE_PAGE_SCHOOL_DASHBOARD_CREATE_USER ("/DashboardCreateUser"),
	AJAX_PAGE_PAGE_SCHOOL_DASHBOARD_CONTENT ("/DashboardContentSchool"),
	AJAX_PAGE_PAGE_COUNSELOR_DASHBOARD_CONTENT ("/DashboardContentCounselor"),
	AJAX_PAGE_PAGE_COMMON_DASHBOARD_CONTENT ("/DashboardContentCommon"),
	AJAX_PAGE_PAGE_SCHOOL_MANAGE_PROFILE_TEACHER_CONTENT ("/ManageTeacherProfileContent"),
	AJAX_PAGE_PAGE_SCHOOL_MANAGE_APPROVED_PROFILE_TEACHER_CONTENT ("/ManageApprovedTeacherProfileContent"),
	AJAX_PAGE_PAGE_MANAGE_MANAGE_PROFILE_CONTENT ("/ManageProfileContent"),
	AJAX_PAGE_PAGE_MANAGE_MANAGE_USERLIST_CONTENT ("/ManageUserList"),
	AJAX_PAGE_PAGE_MANAGE_MANAGE_PROFILE_STUDENT_CONTENT ("/ManageProfileStudentContent"),
	AJAX_PAGE_PAGE_MANAGE_MANAGE_PROFILE_FLEX_STUDENT_CONTENT ("/ManageProfileFlexStudentContent"),
	AJAX_PAGE_PAGE_MANAGE_MANAGE_PROFILE_TEACHER_CONTENT ("/ManageProfileTeacherContent"),
	AJAX_PAGE_PAGE_MANAGE_MANAGE_PROFILE_PARENT_CONTENT ("/ManageProfileParentContent"),
	AJAX_PAGE_PAGE_MANAGE_MANAGE_PROFILE_SCHOOL_CONTENT ("/ManageProfileSchoolContent"),
	AJAX_PAGE_SCHOOL_STUDENT_TEACHER_MAPPING_CONTENT ("/school/StudentTeacherMapping"),
	AJAX_PAGE_SCHOOL_PROFILE_MAPPING_CONTENT ("/school/SchoolProfile"),
	AJAX_PAGE_CHOOSE_SCHOOL ("/school-admin/ChooseSchool"),
	AJAX_PAGE_CHOOSE_SCHOOL_CONTENT ("/school-admin/ChooseSchoolContent"),
	AJAX_PAGE_SCHOOL_PROFILE_LIST_MAPPING_CONTENT ("/school/AllSchoolProfile"),
	AJAX_PAGE_SCHOOL_STUDENT_ATTENDANCE_CONTENT ("/school/StudentAttendance"),
	AJAX_PAGE_COMMON_PAYMENT_HISTORY_CONTENT ("/common/PaymentHistoryContent"),
	AJAX_PAGE_SCHOOL_ENQUIRY_REQUEST_CONTENT ("/school/EnquiryRequest"),
	AJAX_PAGE_SCHOOL_CURRENT_SYLLABUS_REQUEST_CONTENT ("/school/CurrentSyllabusRequest"),
	AJAX_PAGE_SCHOOL_CURRENT_SYLLABUS_CONTENT ("/school/CurrentSyllabusContent"),
	AJAX_PAGE_SCHOOL_PREVIOUS_SYLLABUS_REQUEST_CONTENT ("/school/PreviousSyllabusRequest"),
	AJAX_PAGE_SCHOOL_STUDENT_PAYMENT_HISTORY_CONTENT ("/school/StudentPaymentHistory"),
	AJAX_PAGE_SCHOOL_STUDENT_PAYMENT_HISTORY_DETAILS_CONTENT ("/school/StudentPaymentHistoryDetails"),
	AJAX_PAGE_SCHOOL_CONFLICTED_USER_LIST_CONTENT ("/school/ConflictedUserDetails"),
	AJAX_PAGE_SCHOOL_REVIEW_SCHOOL_PAYMENT ("/school/ReviewSchoolPayment"),
	
	AJAX_PAGE_SCHOOL_SCHOOL_EVALUATION_FORM_B2B ("/school/SchoolEvaluationForm"),
	AJAX_PAGE_SCHOOL_SCHOOL_DATE_OF_VISIT_B2B ("/school/SchoolDateOfVisit"),
	AJAX_PAGE_SCHOOL_SCHOOL_DATE_OF_VISIT_CONTENT_B2B ("/school/SchoolDateOfVisitContent"),
	AJAX_PAGE_SCHOOL_PROSPECTIVE_FORM_B2B ("/school/ProspectiveForm"),
	AJAX_PAGE_SCHOOL_PROSPECTIVE_FORM_CONTENT_B2B ("/school/ProspectiveFormContent"),
	AJAX_PAGE_SCHOOL_EVALUATION_FORM_B2B ("/school/EvaluationForm"),
	AJAX_PAGE_SCHOOL_PROFESSIONAL_DEVELOPMENT_B2B ("/school/ProfessionalDevelopment"),
	AJAX_PAGE_SCHOOL_PROSPECTIVE_REPORT_B2B ("/school/ProspectiveReport"),
	AJAX_PAGE_SCHOOL_PARTNERSHIP_FEE_B2B ("/school/PartnershipFee"),
	AJAX_PAGE_SCHOOL_PARTNERSHIP_CERTIFICATE_B2B ("/school/PartnershipCertificate"),
	AJAX_PAGE_SCHOOL_STUDENT_LIST_B2B ("/school/StudentList"),
	AJAX_PAGE_SCHOOL_STUDENT_BUCKET_LIST_B2B ("/school/StudentBucketList"),
	AJAX_PAGE_SCHOOL_STUDENT_LIST_CONTENT_B2B ("/school/StudentListContent"),
	AJAX_PAGE_SCHOOL_ADD_STUDENT_B2B ("/school/AddStudent"),
	AJAX_PAGE_SCHOOL_STUDENT_PREVIOUS_SUBJECTS_B2B ("/school/StudentPreviousSubjectsContent"),
	AJAX_PAGE_SCHOOL_ADD_LMS_USER ("/StudentLmsCreated"),
	AJAX_PAGE_SCHOOL_STUDENT_NO_LMS_USER ("/StudentListLmsNotCreated"),
	AJAX_PAGE_SCHOOL_STUDENT_LMS_USER ("/StudentListLmsCreated"),
	AJAX_PAGE_SCHOOL_STUDENT_PROFILE_VIEW ("/school/StudentProfileView"),
	AJAX_PAGE_SCHOOL_STUDENT_EDIT_PROFILE_VIEW ("/school/StudentEditProfileView"),
	AJAX_PAGE_SCHOOL_STUDENT_FEE_LIST_CONTENT_B2B ("/school/StudentFeeListContent"),
	AJAX_PAGE_SCHOOL_STUDENT_MARKS_CONTENT_B2B ("/school/StudentMarksListContent"),
	AJAX_PAGE_SCHOOL_STUDENT_TRANSCRIPT_CONTENT_B2B ("/school/StudentTranscriptListContent"),
	AJAX_PAGE_SCHOOL_STUDENT_DIPLOMA_CONTENT_B2B ("/school/StudentDiplomaContent"),
	AJAX_PAGE_SCHOOL_ADD_STUDENT_MARKS_CONTENT_B2B ("/school/AddMarksContent"),
	AJAX_PAGE_SCHOOL_ADD_SUBJECT_B2B ("/school/AddSubject"),
	AJAX_PAGE_SCHOOL_SUBJECT_LIST_B2B ("/school/SubjectListContent"),
	AJAX_PAGE_SCHOOL_GRADE_LIST_B2B ("/school/MarkGradeList"),
	AJAX_PAGE_SCHOOL_EDIT_SUBJECT_B2B ("/school/SubjectB2B"),
	AJAX_PAGE_SCHOOL_EDIT_PRESUBJECT_B2B ("/school/SubjectPreB2B"),
	AJAX_PAGE_SCHOOL_ADD_PRESUBJECT_B2B ("/school/AddPreSubject"),
	AJAX_PAGE_SCHOOL_PRESUBJECT_LIST_B2B ("/school/SubjectPreListContent"),
	AJAX_PAGE_SCHOOL_PAID_FEE_CONTENT_B2B ("/school/PaidFeeContent"),
	AJAX_PAGE_PAGE_STUDENT_B2B_TRANSCRIPT_CONTENT ("/school/StudentB2BTranscript"),
	AJAX_PAGE_SCHOOL_ANNUAL_DUES_CONTENT_B2B ("/school/AnnualDuesContent"),
	AJAX_PAGE_PAGE_STUDENT_B2B_DIPLOMA_CONTENT ("/school/StudentB2BDiploma"),
	AJAX_PAGE_PAGE_STUDENT_B2B_SHOW_TRANSCRIPT ("/school/StudentShowTranscript"),
	AJAX_PAGE_PAGE_STUDENT_SEMESTER_TRANSCRIPT ("/school/StudentSemesterTranscript"),
	AJAX_PAGE_PAGE_STUDENT_TRANSCRIPT_ODDY ("/school/StudentTranscriptOddy"),
	AJAX_PAGE_PAGE_SCHOOL_B2B_SHOW_RECEIPT ("/school/SchoolPaymentReceipt"),
	AJAX_PAGE_PAGE_SCHOOL_B2B_MANAGE_RM ("/school-admin/AddRM"),
	AJAX_PAGE_PAGE_ADMIN_REPORT ("/school-admin/UploadReport"),
	AJAX_PAGE_PAGE_SCHOOL_B2B_EDIT_RM ("/school/AddRMContent"),
	AJAX_PAGE_SCHOOL_B2B_INQUIRY ("/school/SchoolB2BInquiry"),
	PAGE_PAGE_STUDENT_COURSE_SELECTION ("/student/StudentCourseSelection"),
	PAGE_PAGE_STUDENT_SEMESTER_START_DATE_ENTRY ("/student/StudentSemesterStartDateEntrySelection"),
	PAGE_PAGE_STUDENT_SEMESTER_START_DATE_ENTRY1 ("/student/StudentSemesterStartDateEntrySelection1"),
	PAGE_STUDENT_SEMESTER_CONTENT_ENTRY ("/student/StudentAddNewSemesterSection"),						
	AJAX_PAGE_AUDITOR_AUDITOR_PREVIOUSLY_SUBMITTED_REPORTS ("/auditor/PreviouslySubmittedReports"),
	AJAX_PAGE_AUDITOR_AUDITOR_SUBMITTED_EVALUATION ("/auditor/SubmittedEvaluation"),
	AJAX_PAGE_AUDITOR_AUDITOR_SAVED_EVALUATION ("/auditor/SavedEvaluation"),
	AJAX_PAGE_AUDITOR_AUDITOR_PENDING_REPORTS ("/auditor/PendingReports"),
	AJAX_PAGE_AUDITOR_AUDITOR_EDIT_EVALUATION_FORM ("/auditor/EditEvaluationForm"),
	AJAX_PAGE_AUDITOR_AUDITOR_View_EVALUATION_FORM ("/auditor/ViewEvaluationForm"),
	AJAX_PAGE_AUDITOR_AUDITOR_HTML_View_EVALUATION_FORM ("/auditor/HTMLViewEvaluationForm"),
	
	AJAX_PAGE_SCHOOL_CURRENT_TASK_REQUEST_CONTENT ("/school/CurrentTaskRequest"),
	AJAX_PAGE_SCHOOL_PREVIOUS_TASK_REQUEST_CONTENT ("/school/PreviousTaskRequest"),
	AJAX_PAGE_TEACHER_QUESTIONS_CONTENT ("/school/TeacherQuestionList"),//TO DO
	AJAX_PAGE_TEACHER_QUESTIONS_ANSWER_CONTENT ("/school/TeacherQuestionAnswerList"),//TO DO
	AJAX_PAGE_SCHOLARSHIP_ANSWER_CONTENT ("/school/ScholarShip"),//TO DO
	AJAX_PAGE_MEETING_SLOTS_CONTENT ("/school/MeetingSlotsList"),//TO DO
	AJAX_PAGE_REQUEST_DEMO_MEETING_SLOTS_CONTENT ("/school/RequstDemoMeetSlotsList"),//TO DO
	AJAX_PAGE_STUDENT_MANAGE_SESSION_CONTENT ("/school/StudentManageSession"),
	AJAX_PAGE_ONLINE_USER_CONTENT ("/school/OnlineUserLive"),//TO DO
	AJAX_PAGE_STUDENT_TEACHER_LINKING_CONTENT ("/school/StudentTeacherLinkingContent"),
	AJAX_PAGE_STUDENT_TEACHER_MAPPING_LOG_CONTENT ("/school/StudentTeacherMappingLogContent"),
	AJAX_PAGE_ASSIGN_STUDENT_TEACHER_CONTENT ("/school/AssignStudentTeacherContent"),
	AJAX_PAGE_SWPR_CONTENT ("/school/StudentWeeklyProgressReport"),
	AJAX_PAGE_SWPR_CONTENT_FOR_STUDENT ("/school/StudentWeeklyProgressReportContent"),
	AJAX_PAGE_SEMESTER_MARKS_CONTENT ("/school/StudentSemesterMarksContent"),
	AJAX_PAGE_SWPR_VIEW_FOR_STUDENT ("/school/StudentWeeklyProgressReportView"),
	AJAX_PAGE_ENABLED_DATE ("/school/EnabledDateList"),//TO DO
	AJAX_PAGE_SEARCH_BY_ENABLED_DATE ("/school/EnabledDateBySearchDataList"),
	AJAX_PAGE_REQUEST_DEMO_CONTENT ("/common/DemoRequestContent"),
	AJAX_PAGE_REQUEST_DEMO_SCHOOL_CONTENT ("/common/DemoRequestContentSchool"),
	AJAX_PAGE_LMS_STUDENT_MAIL_REQUEST ("/common/LmsStudentPerformanceTrack"),
	AJAX_PAGE_PPC_REQUEST_CONTENT ("/ppc/PPCRequestContent"),
	PAGE_PPC_COMMENTS_REQUES_CONTENT("/ppc/PPCCommentsContent"),
	PAGE_COMMON_COMMENTS_REQUEST_CONTENT("/common/CommonCommentsContent"),
	AJAX_PAGE_PAGE_STUDENT_DASHBOARD_CONTENT ("/DashboardContentStudent"),
	AJAX_PAGE_PAGE_STUDENT_ADDONS_CONTENT ("/student/AddonsStudentSubject"),
	AJAX_PAGE_PAGE_STUDENT_SUBJECTPLAN_CONTENT ("/student/BookSessionPaymentModal"),
	AJAX_PAGE_PAGE_STUDENT_BOOKSESSION_TERM_CONTENT ("/student/BookSessionTermModal"),
	
	AJAX_PAGE_PAGE_STUDENT_STUDENT_TASK_CONTENT ("/student/StudentTask"),
	AJAX_PAGE_PAGE_STUDENT_STUDENT_TEACHER_REQUEST_CONTENT ("/student/StudentTeacherRequest"),
	AJAX_PAGE_PAGE_STUDENT_USER_TUTUTORIAL_CONTENT ("/student/StudentUserGuide"),
	AJAX_PAGE_PAGE_STUDENT_POST_SECONDARY_CONTENT ("/student/StudentPostSecondary"),
	AJAX_PAGE_PAGE_STUDENT_SYLLABUS_CONTENT("/common/SyllabusView"),
	AJAX_PAGE_PAGE_STUDENT_TASK_CONTENT("/student/TaskView"),
	AJAX_PAGE_PAGE_STUDENT_STUDENT_COURSE_TIMING_CONTENT ("/student/StudentCourseTiming"),
	AJAX_PAGE_PAGE_STUDENT_STUDENT_EVENTS_CONTENT ("/common/SchoolEvents"),//TO DO
	AJAX_PAGE_PAGE_STUDENT_STUDENT_EXAM_DETAILS_CONTENT ("/student/StudentExamDetails"),//TO DO
	AJAX_PAGE_PAGE_STUDENT_STUDENT_PERFORMANCE_CONTENT ("/student/StudentPerformance"),
	AJAX_PAGE_PAGE_STUDENT_STUDENT_PTM_REPORT_CONTENT ("/student/StudentPtmReport"),
	AJAX_PAGE_PAGE_STUDENT_STUDENT_DUE_FEES_CONTENT ("/student/StudentDueFees"),
	AJAX_PAGE_PAGE_STUDENT_STUDENT_VIEW_RECEIPT_CONTENT ("/student/StudentViewReceipt"),
	AJAX_PAGE_PAGE_STUDENT_STUDENT_VIEW_RECEIPT_CONTENT_HTML ("/student/StudentViewReceiptHTML"),
	AJAX_PAGE_PAGE_STUDENT_STUDENT_TRANSCRIPT_CONTENT ("/student/StudentTranscript"),
	AJAX_PAGE_PAGE_SCHOOL_TRAVEL_DETAILS_CONTENT ("/school/TravelDetailsContent"),
	AJAX_PAGE_PAGE_SCHOOL_ASSIGN_RM_CONTENT ("/school/AssignRMContent"),
	AJAX_PAGE_PAGE_SCHOOL_VIEW_RM_CONTENT("/school/ViewRMContent"),
	AJAX_PAGE_PAGE_SCHOOL_MANAGE_SUBJECTS_CONTENT ("/school-admin/ManageSubjectContent"),
	AJAX_PAGE_PAGE_SCHOOL_LIST_FOR_REQ_SUBJECTS_CONTENT ("/school-admin/SchoolListForReqSubjects"),
	AJAX_PAGE_SCHOOL_SUBJECT_LIST_REQUESTED_CONTENT ("/school-admin/SubjectListContent"),
	AJAX_PAGE_SCHOOL_PRESUBJECT_LIST_REQUESTED_CONTENT ("/school-admin/SubjectPreListContent"),
	AJAX_PAGE_PAGE_SCHOOL_TRAVEL_DETAILS_VIEW_CONTENT ("/school/TravelDetailsView"),
	AJAX_PAGE_PAGE_USER_ACTIVITY ("/common/UserActivity"),
	AJAX_PAGE_PAGE_SCHOOL_REMARKS_HISTORY ("/school-admin/RemarksHistoryContent"),
	AJAX_PAGE_PAGE_STUDENT_COURSE_CONTENT ("/student/CourseListContent"),
	AJAX_PAGE_PAGE_MANAGE_PROVIDER_CONTENT ("/school/CourseProviderListContent"),
//	AJAX_PAGE_PAGE_STUDENT_PLACEMENT_COURSE_CONTENT ("/student/PlacementCourseListContent"),
	AJAX_PAGE_STUDENT_ADD_EDIT_COURSE_CONTENT ("/student/AddCourse"),
	AJAX_PAGE_PAGE_STUDENT_SUBJECT_CONTENT ("/student/SubjectListContent"),
	AJAX_PAGE_STUDENT_ADD_EDIT_SUBJECT_CONTENT ("/student/AddSubject"),
	AJAX_PAGE_SCHOOL_ASSIGN_SCHOLARSHIP_STUDENT_CONTENT ("/school/ViewScholarshipAssighnedUserList"),
	AJAX_PAGE_TEACHER_TAUGHT_SUBJECT ("/teacher/TeacherSubjectTaughtModel"),
	AJAX_PAGE_TEACHER_PREFERRED_SUBJECT ("/teacher/TeacherPreferredSubjectModel"),
	AJAX_PAGE_PAGE_TEACHER_DASHBOARD_CONTENT ("/DashboardContentTeacher"),
	AJAX_PAGE_TEACHER_SYLLABUS_CONTENT ("/teacher/SyllabusList"),
	AJAX_PAGE_TEACHER_TASK_CONTENT("/teacher/TaskList"),
	AJAX_PAGE_TEACHER_STUDENT_TASK_CONTENT("/teacher/StudentTaskSubmitList"),
	AJAX_PAGE_PTM_MEETING_SLOTS_CONTENT ("/teacher/PTMMeetingSlotsList"),//TO DO
	AJAX_PAGE_ASSIGNED_STUDENTS_CONTENT ("/teacher/AssignedStudents"),
	AJAX_PAGE_TEACHER_CREATE_SESSION ("/teacher/CreateSession"),
	AJAX_PAGE_CALENDAR ("/school/Calendar"),
	AJAX_PAGE_CALENDAR_SLOT ("/school/CalendarDateSlotList"),
	AJAX_PAGE_PAGE_TEACHER_VIEW_AGREEMENT_CONTENT("/common/TeacherAgreementView"),
	AJAX_PAGE_PAGE_TEACHER_EDIT_AGREEMENT_CONTENT("/common/TeacherAgreementEdit"),
	AJAX_PAGE_PAGE_TEACHER_DASHBOARD_USER_CONTENT("/common/DashboardTeacherUserContent"),
	AJAX_PAGE_PAGE_TEACHER_AGREEMENT_CONTENT("/common/TeacherAgreement"),
	AJAX_PAGE_PAGE_TEACHER_AGREEMENT_VIEWONLY_CONTENT("/common/TeacherAgreementViewOnly"),
	AJAX_PAGE_STUDENT_TEACHER_SESSION_REPORT ("/school/StudentTeacherSessionReport"),
	
	AJAX_PAGE_PAGE_PARENT_DASHBOARD_CONTENT ("/DashboardContentParent"),
	AJAX_PAGE_PARENT_TASK_CONTENT ("/parent/ParentStudentTask"),
	AJAX_PAGE_PARENT_RECEIPT_CONTENT ("/parent/ParentStudentDueFees"),
	AJAX_PAGE_PTM_BOOKED_SLOTS_CONTENT ("/parent/BookePTMSlotsList"),//TO DO
	AJAX_PAGE_PTM_ATTEMPT_SLOTS_CONTENT ("/parent/AttemptPTMSlotsList"),//TO DO
	
	AJAX_PAGE_PAGE_ADMIN_DASHBOARD_CONTENT ("/DashboardContentAdmin"),
	
	AJAX_PAGE_COMMON_DELETE_USER_CONTENT ("/common/DeleteUser"),
	AJAX_PAGE_COMMON_ATTENDANCE_CONTENT ("/common/Attendance"),
	AJAX_PAGE_COMMON_STUDENT_ATTENDANCE_CONTENT ("/common/StudentLoginAttendance"),
	AJAX_PAGE_COMMON_EMAIL_COMPOSE_CONTENT ("/common/EmailCompose"),
	AJAX_PAGE_COMMON_EMAIL_INBOX_CONTENT ("/common/EmailInbox"),
	AJAX_PAGE_COMMON_EMAIL_SENT_CONTENT ("/common/EmailSent"),
	AJAX_PAGE_COMMON_EMAIL_DETAIL_CONTENT ("/common/EmailDetails"),
	
	AJAX_PAGE_COMMON_PROFILE_VIEW_CONTENT ("/common/ProfileView"),
	AJAX_PAGE_COMMON_ADMIN_STUDENT_PROFILE_VIEW_CONTENT ("/student/AdminStudentProfileView"),
	AJAX_PAGE_PAGE_MANAGE_PARENT_PROFILE_STUDENT_CONTENT ("/student/AdminParentStudentProfileView"),
	AJAX_PAGE_COMMON_ADMIN_TEACHER_PROFILE_VIEW_CONTENT ("/teacher/AdminTeacherProfileView"),
	AJAX_PAGE_COMMON_ADMIN_APPROVE_TEACHER_PROFILE_VIEW_CONTENT ("/teacher/AdminApproveTeacherProfileView"),
	AJAX_PAGE_COMMON_ADMIN_REJECT_TEACHER_PROFILE_VIEW_CONTENT ("/teacher/AdminRejectTeacherProfileView"),
	AJAX_PAGE_COMMON_UPDATE_PROFILE_CONTENT ("/common/UpdateProfile"),
	AJAX_PAGE_ADD_COURSE_TO_TEACHER_CONTENT ("/teacher/AddCourseToTeacherContent"),
	AJAX_PAGE_NOTIFICATIONS ("/common/Notifications"),
	AJAX_PAGE_SMILE ("/buy-a-smile/BuyASmile"),
	AJAX_PAGE_SMILE_VIEW_RECIEPT ("/buy-a-smile/BuyASmileViewReciept"),
	AJAX_PAGE_SMILE_PAYMENT_SUCCESS ("/buy-a-smile/SmilePaymentSuccessful"),
	AJAX_PAGE_SMILE_PAYMENT_UNSUCCESS ("/buy-a-smile/SmilePaymentUnSuccessful"),
	AJAX_PAGE_SCHOOL_ADMIN_PROFILE_VIEW_CONTENT ("/school-admin/SchoolProfileView"),
	AJAX_PAGE_SCHOOL_ADMIN_REJECT_PROFILE_VIEW_CONTENT ("/school-admin/RejectSchoolProfileView"),
	AJAX_PAGE_COMMON_CHANGED_PASSWORD_CONTENT ("/common/ChangedPassword"),
	AJAX_PAGE_COMMON_NOTIFICATION_COMPOSE_CONTENT ("/common/NotificationCompose"),
	AJAX_PAGE_COMMON_NOTIFICATION_INBOX_CONTENT ("/common/NotificationInbox"),
	AJAX_PAGE_COMMON_NOTIFICATION_SENT_CONTENT ("/common/NotificationSent"),
	AJAX_PAGE_COMMON_VIEW_TASK_CONTENT ("/common/ViewTask"),
	AJAX_PAGE_COMMON_TICKET_RAISED_CONTENT ("/common/TicketRaised"),
	AJAX_PAGE_COMMON_TICKET_RAISED_LISTING ("/common/TicketRaisedListing"),
	AJAX_PAGE_COMMON_TICKET_RAISED_USER_INFO ("/common/TicketRaisedUserInfo"),
	AJAX_PAGE_COMMON_MAINTENANCE_DOWN_MESSAGE ("/common/MaintenanceDownMessage"),
	
	AJAX_PAGE_PAGE_MANAGE_COUNSELOR_DASHBOARD_CONTENT("/counselor/DashboardManageCounselor"),
	AJAX_PAGE_PAGE_SUPADMIN_ADD_COUNSELOR_CONTENT("/counselor/DashboardAddCounselor"),
	AJAX_PAGE_PAGE_SUPADMIN_VIEW_COUNSELOR_CONTENT("/counselor/DashboardViewCounselor"),
	AJAX_PAGE_PAGE_MANAGE_COUNSELOR_STUDENT_DASHBOARD_CONTENT("/counselor/DashboardManageCounselorStudent"),
	AJAX_PAGE_PAGE_MANAGE_COUNSELOR_REFERRAL_DASHBOARD_CONTENT("/counselor/DashboardManageCounselorReferral"),
	
	AJAX_PAGE_MODULE_REQUEST ("/modules/ModuleList"),
	AJAX_PAGE_ROLE_REQUEST ("/role/RolesList"),
	AJAX_PAGE_ROLE_RIGHTS_REQUEST ("/role/RoleRightsModule"),
	AJAX_PAGE_RIGHTS_LIST_REQUEST ("/role/RightsModuleList"),
	
	PAGE_SIGNUP_NUMBER ("signupPage"),
	PAGE_SIGNUP_STUDENT ("student/SignupStudent"),
	PAGE_SIGNUP_STUDENT1 ("student/SignupStudentStage1"),
	PAGE_SIGNUP_STUDENT2 ("student/SignupStudentStage2"),
	PAGE_SIGNUP_STUDENT3 ("student/SignupStudentStage3"),
	PAGE_SIGNUP_STUDENT4 ("student/SignupStudentStage4"),
	PAGE_SIGNUP_STUDENT5 ("student/SignupStudentStage5"),
	PAGE_SIGNUP_STUDENT6 ("student/SignupStudentStage6"),
	PAGE_SIGNUP_STUDENT7 ("student/SignupStudentStage7"),
	PAGE_SIGNUP_COURSE_CATALOG ("student/SubjectCatalog"),
	PAGE_SIGNUP_CTE_COURSE_CATALOG ("student/CTESubjectCatalogue"),
	
	PAGE_SIGNUP_FLEXCOURSE_CONFIRMATION ("flexCourse/SignupFlexCourseConfirmation"),
	PAGE_SIGNUP_FLEXCOURSE_STUDENT ("flexCourse/SignupStudent"),
	PAGE_SIGNUP_FLEXCOURSE_STUDENT1 ("flexCourse/SignupStudentStage1"),
	PAGE_SIGNUP_FLEXCOURSE_STUDENT2 ("flexCourse/SignupStudentStage2"),
	PAGE_SIGNUP_FLEXCOURSE_STUDENT3 ("flexCourse/SignupStudentStage3"),
	PAGE_SIGNUP_FLEXCOURSE_STUDENT4 ("flexCourse/SignupStudentStage4"),
	PAGE_SIGNUP_FLEXCOURSE_STUDENT5 ("flexCourse/SignupStudentStage5"),
	PAGE_SIGNUP_FLEXCOURSE_STUDENT6 ("flexCourse/SignupStudentStage6"),
	PAGE_SIGNUP_FLEXCOURSE_COURSE_CATALOG ("flexCourse/SubjectCatalog"),
	AJAX_PAGE_SIGNUP_FLEXCOURSE_DETAILS ("flexCourse/SignupCourseDetails"),
	AJAX_PAGE_SIGNUP_FLEXSUBJECT_DETAILS ("flexCourse/SignupStudentStage1Content"),
	AJAX_PAGE_SIGNUP_FLEXSUBJECT_SEARCH ("flexCourse/SignupStudentStage1Content"),
	AJAX_PAGE_SIGNUP_FLEX_SUBJECT_VIEW_DETAILS ("flexCourse/SignupFlexCourseDetails"),
	
	PAGE_SIGNUP_VOCAIONAL_STUDENT ("studentVocational/SignupStudent"),
	PAGE_SIGNUP_VOCAIONAL_STUDENT1 ("studentVocational/SignupStudentStage1"),
	PAGE_SIGNUP_VOCAIONAL_STUDENT2 ("studentVocational/SignupStudentStage2"),
	PAGE_SIGNUP_VOCAIONAL_STUDENT3 ("studentVocational/SignupStudentStage3"),
	PAGE_SIGNUP_VOCAIONAL_STUDENT4 ("studentVocational/SignupStudentStage4"),
	PAGE_SIGNUP_VOCAIONAL_STUDENT5 ("studentVocational/SignupStudentStage5"),
	PAGE_SIGNUP_VOCAIONAL_STUDENT6 ("studentVocational/SignupStudentStage6"),
	PAGE_SIGNUP_VOCAIONAL_STUDENT7 ("studentVocational/SignupStudentStage7"),
	PAGE_SIGNUP_VOCAIONAL_COURSE_CATALOG ("studentVocational/SubjectCatalog"),
	
	//AJAY RESPONSE IN HTML
	AJAX_PAGE_SIGNUP_SAVE_USER_DETAILS ("student/SignupStudentStage1"),
	AJAX_PAGE_SIGNUP_SAVE_STUDENT_DETAILS ("student/SignupStudentStage2"),
	AJAX_PAGE_SIGNUP_SAVE_PARENT_DETAILS ("student/SignupStudentStage3"),
	AJAX_PAGE_SIGNUP_SAVE_ADDRESS_DETAILS ("student/SignupStudentStage4"),
	AJAX_PAGE_SIGNUP_SAVE_COURSE_DETAILS ("student/SignupStudentStage5"),
	AJAX_PAGE_SIGNUP_SAVE_CONFIRM_AND_PAY_DETAILS ("student/SignupStudentStage6"),
	AJAX_PAGE_SIGNUP_COURSE_DETAILS ("student/SignupCourseDetails"),
	AJAX_PAGE_SIGNUP_COURSE_DETAILS_CONTENT ("student/SignupCourseDetailsContent"),
	AJAX_PAGE_COMMON_ATTACHMENT_VIEW("/common/AttachmentViewer"),
	AJAX_PAGE_STUDENT_CREATE_SESSION ("/student/StudentCreateSession"),
	AJAX_PAGE_STUDENT_BOOK_SESSION ("/student/AddonsBookSessionStudentSubject"),
	AJAX_PAGE_STUDENT_FREE_SLOTS("/student/StudentFreeSlots"),
	AJAX_PAGE_SIGNUP_SUBJECT_VIEW_DETAILS ("student/CourseContentDetails"),
	
	//Next Session
	AJAX_PAGE_NEXTSESSION_COURSE ("dashboard/student/StudentNextSessionCourses"),
	AJAX_PAGE_NEXTSESSION_COURSE_DETAILS ("dashboard/student/StudentNextSessionCoursesContent"),
	AJAX_PAGE_NEXTSESSION_COURSE_REVIEW ("dashboard/student/StudentNextSessionPaymentReview"),
	AJAX_PAGE_NEXTSESSION_CTE_COURSE_CATALOGUE ("dashboard/student/NextSessionCTESubjectCatalogue"),
	
	PAGE_SIGNUP_TEACHER ("teacher/SignupTeacher"),
	PAGE_SIGNUP_TEACHER1 ("teacher/SignupTeacherStage1"),
	PAGE_SIGNUP_TEACHER2 ("teacher/SignupTeacherStage2"),
	PAGE_SIGNUP_TEACHER3 ("teacher/SignupTeacherStage3"),
	PAGE_SIGNUP_TEACHER4 ("teacher/SignupTeacherStage4"),
	PAGE_SIGNUP_TEACHER5 ("teacher/SignupTeacherStage5"),
	PAGE_SIGNUP_TEACHER6 ("teacher/SignupTeacherStage6"),
	
		
	//AJAY RESPONSE IN HTML
	AJAX_PAGE_SIGNUP_SAVE_TEACHER_USER_DETAILS ("teacher/SignupTeacherStage1"),
	AJAX_PAGE_SIGNUP_SAVE_TEACHER_BASIC_DETAILS ("teacher/SignupTeacherStage2"),
	AJAX_PAGE_SIGNUP_SAVE_TEACHER_UPDATE_PROFILE_DETAILS ("teacher/SignupTeacherStage3"),
	AJAX_PAGE_SIGNUP_SAVE_TEACHER_REVIEW_DETAILS ("teacher/SignupTeacherStage4"),
	AJAX_PAGE_SIGNUP_SAVE_TEACHER_INTERVIEW_DETAILS ("teacher/SignupTeacherStage5"),
	AJAX_PAGE_SIGNUP_TEACHER_QUESTIONS_DETAILS ("teacher/SignupTeacherStage5ContentTraining"),
	AJAX_PAGE_SIGNUP_SAVE_TEACHER_TRAINING_DETAILS ("teacher/SignupTeacherStage6"),
	AJAX_PAGE_SIGNUP_SAVE_TEACHER_CONTACT_ACCOUNT_DETAILS ("teacher/SignupTeacherStage7"),
	
	
	
	PAGE_SIGNUP_SCHOOL ("school/SignupSchool"),
	PAGE_SIGNUP_SCHOOL1 ("school/SignupSchoolStage1"),
	PAGE_SIGNUP_SCHOOL2 ("school/SignupSchoolStage2"),
	PAGE_SIGNUP_SCHOOL3 ("school/SignupSchoolStage3"),
	PAGE_SIGNUP_SCHOOL4 ("school/SignupSchoolStage4"),
	PAGE_SIGNUP_SCHOOL5 ("school/SignupSchoolStage5"),
	PAGE_SIGNUP_SCHOOL6 ("school/SignupSchoolStage6"),
	PAGE_SIGNUP_SCHOOL7 ("school/SignupSchoolStage7"),
	
	HTML_PAGE_SCHOOL_CONTRACT_B2B ("school/SchoolContract"),
	
	COMMON_PAYMENT_RESPONSE ("common/CommonPaymentResponse"),
		
	//AJAY RESPONSE IN HTML
	AJAX_PAGE_SIGNUP_SAVE_SCHOOL_USER_DETAILS ("school/SignupSchoolStage1"),
	AJAX_PAGE_SIGNUP_SAVE_SCHOOL_BASIC_DETAILS ("school/SignupSchoolStage2"),
	AJAX_PAGE_SIGNUP_SAVE_SCHOOL_UPDATE_PROFILE_DETAILS ("school/SignupSchoolStage3"),
	AJAX_PAGE_SIGNUP_SAVE_SCHOOL_REVIEW_DETAILS ("school/SignupSchoolStage4"),
	AJAX_PAGE_SIGNUP_SAVE_SCHOOL_INTERVIEW_DETAILS ("school/SignupSchoolStage5"),
	AJAX_PAGE_SIGNUP_SCHOOL_QUESTIONS_DETAILS ("school/SignupSchoolStage5ContentTraining"),
	AJAX_PAGE_SIGNUP_SAVE_SCHOOL_TRAINING_DETAILS ("school/SignupSchoolStage6"),
	AJAX_PAGE_SIGNUP_SAVE_SCHOOL_CONTACT_ACCOUNT_DETAILS ("school/SignupSchoolStage7"),
	
	PAGE_REQUEST_DEMO("requestDemo/RequestDemo"),
	PAGE_REQUEST_DEMO_1("requestDemo/RequestDemo1"),
	PAGE_REQUEST_DEMO_2("requestDemo/RequestDemo2"),
	PAGE_REQUEST_DEMO_3("requestDemo/RequestDemo3"),
	PAGE_REQUEST_DEMO_FREE_SLOTS("requestDemo/RequestDemoFreeSlots"),
	PAGE_REQUEST_DEMO_THANK_YOU("requestDemo/RequestDemoThankYou"),
	PAGE_PPC_REQUEST("ppc/PPCRequest"),
	PAGE_PPC_REQUEST_1("ppc/PPCRequest1"),
	PAGE_PPC_REQUEST_2("ppc/PPCRequest2"),

	PAGE_PAYMENT_HISTORY_CONTENT("/common/CommonPaymentHistoryContent"),
	
	REQUEST_KEY_ERROR_CODE ("0100"),
	REQUEST_KEY_ERROR_MESSAGE ("REQUEST KEY IS NOT AVAILABLE IN REQUEST DATA BODY OR INVALID"),
	
	DATE_FORMAT_DOB ("MM-dd-yyyy"),
	CLIENT_COMMON_PAYMENT("/common/ClientCommonPayment"),
	
	AJAX_PAGE_TIPS_FOR_EDUCATOR ("/TipsForEducator");
	
	private String value;
	private ClientConstant(final String value){
		this.value = value;
	}
	public String getValue() {
		return value;
	}
}
