package com.training.v1.constant;

public enum EnrolmentType {
	REGISTRATION_FRESH, REGISTRATION_NEXT_GRADE, REGISTRATION_COMPLETE_GRADES, REGISTRATION_IMPORVE_GRADES, REGISTRATION_FLEX_COURSE, REGISTRATION_REGISTER;
}