package com.training.v1.constant;

public enum SeriConstant {
	
	CONTROL_TYPE_ADD("ADD"),
	CONTROL_TYPE_EMAIL("EMAIL"),
	CONTROL_TYPE_MARQUEE("MARQUEE"),
	CONTROL_TYPE_EDIT("EDIT"),
	CONTROL_TYPE_VIEW("VIEW"),
	CONTROL_TYPE_VIEW_UUID("VIEW_UUID"),
	CONTROL_TYPE_ACTIVE("ACTIVE"),
	CONTROL_TYPE_INACTIVE("INACTIVE"),
	CONTROL_TYPE_LIST("LIST"),
	CONTROL_TYPE_COUNT("COUNT"),
	CONTROL_TYPE_SEEN("SEEN"),
	CONTROL_TYPE_DELETE("DELETE"),
	
	PROPERTY_NAME_DATABASE_DRIVER  ("spring.datasource.driver-class-name"),
	PROPERTY_NAME_DATABASE_URL  ("spring.datasource.url"),
	PROPERTY_NAME_DATABASE_USERNAME  ("spring.datasource.username"),
	PROPERTY_NAME_DATABASE_PASSWORD  ("spring.datasource.password"),
	PROPERTY_NAME_JPA_DDL_UPDATE  ("spring.jpa.hibernate.ddl-auto"),
	PROPERTY_NAME_JPA_DIALECT  ("spring.jpa.database-platform"),
	PROPERTY_NAME_JPA_SHOW_SQL  ("spring.jpa.show-sql"),
	PROPERTY_NAME_TOMCAT_INITIAL_SIZE  ("spring.datasource.tomcat.initial-size"),
	PROPERTY_NAME_TOMCAT_MAX_ACTIVE  ("spring.datasource.tomcat.max-active"),
	PROPERTY_NAME_TOMCAT_MAX_IDLE  ("spring.datasource.tomcat.max-idle"),
	PROPERTY_NAME_TOMCAT_JMX_ENABLED  ("spring.datasource.tomcat.jmx-enabled"),
	PROPERTY_NAME_TOMCAT_TIME_BETWEEN_EVICTION_RUN  ("spring.datasource.tomcat.time-between-eviction-runs-millis"),
	PROPERTY_NAME_TOMCAT_REMOVE_ABONDONED  ("spring.datasource.tomcat.remove-abandoned"),
	PROPERTY_NAME_TOMCAT_REMOVE_ABONDONED_TIMEOUT  ("spring.datasource.tomcat.remove-abandoned-timeout"),
	PROPERTY_NAME_TOMCAT_REMOVE_ABONDONED_WHEN_PERCENTAGE_FULL  ("spring.datasource.tomcat.abandon-when-percentage-full"),
	PROPERTY_NAME_TOMCAT_TEST_ON_BORROW  ("spring.datasource.tomcat.test-on-borrow"),
	PROPERTY_NAME_TOMCAT_VALIDATION_QUERY  ("spring.datasource.tomcat.validation-query"),
	PROPERTY_NAME_TOMCAT_VALIDATION_INTERVAL  ("spring.datasource.tomcat.validation-interval"),
	TECHNICAL_GLITCH  ("Sorry for inconvenience, system has encountered technical glitch. "),
	UNUSAUAL_MESSAGE ("This happen not happing unusally!"),
	MESSAGE_SESSION_OUT  ("Your session has been timed out, please login again"),
	MESSAGE_INVALID_ROLE_ACCESS  ("Unauthrosied access!!! Please login again"),
	TEMPLATE_TYPE_EMAIL ("1"),
	SCHOOL_SUBSCRIPTION_PRICE_WT ("15%"),
	
	ERROR_CODE ("errorCode="),
	ERROR_MESSAGE ("errorMessage="),
	STATUS_CODE_FAILED ("0"),
	STATUS_CODE_SUCCESS  ("1"),
	STATUS_CODE_EXCEPTION  ("2"),
	STATUS_CODE_EXTERNATAL_ACTIVITY  ("3"),
	STATUS_MSG_FAILED ("FAILED"),
	STATUS_MSG_SUCCESS ("SUCCESS"),
	STATUS_MSG_EXCEPTION ("EXCEPTION"),
	STATUS_MSG_SESSION_OUT ("SESSIONOUT"),
	
	EMAIL_AVAILABLE_KEY ("EMAIL-AVAILABLE"),
	EMAIL_MODULE_KEY ("MODULE-EDIT"),
	EMAIL_ROLE_KEY ("ROLE-EDIT"),
	REFERRAL_AVAILABLE_KEY ("REFERRAL-AVAILABLE"),
	EMAIL_RESEND_KEY ("EMAIL-RESEND"),
	COUNTRY_LIST_KEY ("COUNTRIES-LIST"),
	ROLE_TEACHER ("ROLE_TEACHER"),
	ROLE_SCHOOL ("ROLE_SCHOOL"),
	ROLE_SCHOOL_B2B ("ROLE_SCHOOL_B2B"),
	STATE_LIST_KEY ("STATES-LIST"),
	CITY_LIST_KEY ("CITIES-LIST"),
	GRADE_LIST_KEY ("GRADES-LIST"),
	SUBJECT_LIST_KEY ("SUBJECT-LIST"),
	SUBJECT_LIST_BY_GRADE_KEY("SUBJECT-LIST-BY-GRADE"),
	SUBJECT_LIST_BY_GRADE_TEACHER_KEY("SUBJECT-LIST-BY-GRADE-TEACHER-ID"),
	TEACHER_SUBJECT_LIST_BY_GRADE_KEY("TEACHER_SUBJECT-LIST-BY-GRADE"),
	TEACHER_TAUGHT_SUBJECT_LIST_BY_GRADE_KEY("TEACHER-TAUGHT-SUBJECT-LIST-BY-GRADE"),
	TEACHER_EVENT_SUBJECT_LIST("TEACHER_EVENT_SUBJECT-LIST"),
	SCHOOL_LIST_KEY ("SCHOOLS-LIST"),
	TIMEZONE_LIST_KEY ("TIMEZONE-LIST"),
	DEPARTMENT_LIST_KEY ("DEPARTMENT-LIST"),
	FILE_TYPE_LIST_KEY ("FILE-TYPE-LIST"),
	ROLES_LIST_KEY ("ROLES-LIST"),
	EVENTS_LIST_KEY ("EVENTS-LIST"),
	SYLLABUS_LIST_KEY ("SYLLABUS-LIST"),
	SYLLABUS_LIST_BYID_KEY ("SYLLABUS-BYID-LIST"),
	APPLY_SCHOLARSHIP_KEY ("APPLY-SCHOLARSHIP"),
	LAST_JOB_FROM_MONTHS("LAST-JOB-FROM-MONTHS"),
	LAST_JOB_TO_YEARS("LAST-JOB-TO-YEARS"),
	LAST_JOB_TO_MONTHS("LAST-JOB-TO-MONTHS"),
	MEETINGS_LIST("MEETINGS-LIST"),
	EMAIL_LIST("EMAIL_LIST"),
	SEND_MAIL_FOR_PENDING_APPROVAL("SEND_MAIL_FOR_PENDING_APPROVAL"),
	GET_ACTIVE_SET("GET_ACTIVE_SET"),
	UPDATE_QUESTIONS_ANSWERS("UPDATE_QUESTIONS_ANSWERS"),
	PREVSUBJECT_LIST_KEY ("PREVSUBJECT-LIST"),
	SCHOOL_B2B_STUDENTS_LIST_KEY ("SCHOOL_B2B_STUDENTS_LIST"),
	SCHOOL_B2B_STUDENT_ROLLNo_LIST_KEY ("SCHOOL_B2B_STUDENT_ROLLNo"),
	
	EMAIL_AVAILABLE_CODE_FAILURE ("0001"),
	EMAIL_AVAILABLE_MESSAGE_FAILIRE ("YOU ARE ALREADY REGISTERED WITH K8 School.PLEASE Login to continue."),
	
	REFERRAL_AVAILABLE_CODE_FAILURE ("01001"),
	REFERRAL_AVAILABLE_MESSAGE_FAILIRE ("Referral code is not available, please try again."),
	
	REFERRAL_AVAILABLE_CODE_SUCCESS ("01002"),
	REFERRAL_AVAILABLE_MESSAGE_SUCCESS ("REFERRAL CODE IS AVAILABLE."),
	
	EMAIL_AVAILABLE_CODE_SUCCESS ("0002"),
	EMAIL_AVAILABLE_MESSAGE_SUCCESS ("REQUESTED EMAIL IS AVAILABLE"),
	
	MODULE_AVAILABLE_CODE_SUCCESS ("00021"),
	MODULE_AVAILABLE_MESSAGE_SUCCESS ("SUCCESS"),
	
	MODULE_AVAILABLE_CODE_FAILURE ("0001"),
	MODULE_AVAILABLE_MESSAGE_FAILIRE ("MODULE NOT FOUND"),
	
	EMAIL_AVAILABLE_ERROR_DESCRIPTION ("EITHER REQUEST EMAIL IS NOT VALID OR EMPTY"),
	EMAIL_AVAILABLE_EXCEPTION_CODE ("0003"),
	
	MODULE_AVAILABLE_ERROR_DESCRIPTION ("EITHER REQUEST MODULE IS NOT VALID OR EMPTY"),
	MODULE_AVAILABLE_EXCEPTION_CODE ("0003"),
	
	ROLE_AVAILABLE_ERROR_DESCRIPTION ("EITHER REQUEST ROLE IS NOT VALID OR EMPTY"),
	ROLE_AVAILABLE_EXCEPTION_CODE ("0003"),
	
	REQUEST_OBJECT_ERROR_CODE ("0004"),
	REQUEST_OBJECT_ERROR_MESSAGE ("SERI REQUEST OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	AUTHENTICATION_OBJECT_ERROR_CODE ("0005"),
	AUTHENTICATION_OBJECT_ERROR_MESSAGE ("AUTHENTICATION OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	REQUEST_DATA_OBJECT_ERROR_CODE ("0006"),
	REQUEST_DATA_OBJECT_ERROR_MESSAGE ("REQUEST DATA OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	HASH_ERROR_CODE ("0007"),
	HASH_ERROR_MESSAGE ("HASH IS NOT AVAILABLE IN AUTHENTICATION OBJECT"),
	
	SIGNUP_DATA_OBJECT_ERROR_CODE ("0008"),
	SIGNUP_DATA_OBJECT_ERROR_MESSAGE ("SIGNUP DATA OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	SIGNUP_STUDENT_DATA_OBJECT_ERROR_CODE ("0009"),
	SIGNUP_STUDENT_DATA_OBJECT_ERROR_MESSAGE ("SIGNUP STUDENT DATA OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	SIGNUP_PARENT_DATA_OBJECT_ERROR_CODE ("0010"),
	SIGNUP_PARENT_DATA_OBJECT_ERROR_MESSAGE ("SIGNUP PARENT DATA OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	SIGNUP_EDUCATION_DATA_OBJECT_ERROR_CODE ("0010"),
	SIGNUP_EDUCATION_DATA_OBJECT_ERROR_MESSAGE ("SIGNUP EDUCATION QUALIFICATION DATA OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	SIGNUP_ADDRESS_DATA_OBJECT_ERROR_CODE ("0011"),
	SIGNUP_ADDRESS_DATA_OBJECT_ERROR_MESSAGE ("SIGNUP ADDRESS DATA OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	SIGNUP_COURSE_DATA_OBJECT_ERROR_CODE ("0012"),
	SIGNUP_COURSE_DATA_OBJECT_ERROR_MESSAGE ("SIGNUP COURSE DATA OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	USER_DOES_NOT_EXIST_ERROR_CODE ("0013"),
	USER_DOES_NOT_EXIST_ERROR_MESSAGE ("USER DOES NOT EXISTS"),
	
	STUDENT_DOES_NOT_EXIST_ERROR_CODE ("0014"),
	STUDENT_DOES_NOT_EXIST_ERROR_MESSAGE ("STUDENT DOES NOT EXISTS"),
	
	PARENT_DOES_NOT_EXIST_ERROR_CODE ("0015"),
	PARENT_DOES_NOT_EXIST_ERROR_MESSAGE ("PARENT DOES NOT EXISTS"),
	
	TEACHER_DOES_NOT_EXIST_ERROR_CODE ("0016"),
	TEACHER_DOES_NOT_EXIST_ERROR_MESSAGE ("TEACHER DOES NOT EXISTS"),
	
	SCHOOL_DOES_NOT_EXIST_ERROR_CODE ("0017"),
	SCHOOL_DOES_NOT_EXIST_ERROR_MESSAGE ("SCHOOL DOES NOT EXISTS"),
	
	FORGOT_PASSWORD_AVAILABLE_KEY ("FORGOT-PASSWORD"),
	FORGOT_PASSWORD_MESSAGE_SUCCESS ("Email should be received in the user's mailbox"),
	FORGOT_PASSWORD_MESSAGE_FAILIRE ("REQUESTED EMAIL IS NOT AVAILABLE"),
	FORGOT_PASSWORD_CODE_FAILURE ("0018"),
	FORGOT_PASSWORD_CODE_SUCCESS ("0019"),
	FORGOT_PASSWORD_ERROR_DESCRIPTION ("EITHER REQUEST EMAIL IS NOT VALID OR EMPTY"),
	FORGOT_PASSWORD_EXCEPTION_CODE ("0020"),
	
	EMAIL_RESEND_CODE_SUCCESS ("0021"),
	EMAIL_RESEND_MESSAGE_SUCCESS ("Email should be received in the user's mailbox."),
	
	EMAIL_RESEND_CODE_FAILIRE ("0022"),

	RESET_PASSWORD_AVAILABLE_KEY ("RESET-PASSWORD"),
	RESET_PASSWORD_MESSAGE_SUCCESS ("Password has been changed successfully"),
	RESET_PASSWORD_EMAIL_MESSAGE ("EITHER REQUEST EMAIL IS NOT VALID OR EMPTY"),
	RESET_PASSWORD_MESSAGE_FAILIRE ("REQUESTED PASSWORD DOES NOT MATCH"),
	RESET_PASSWORD_CODE_FAILURE ("0023"),
	RESET_PASSWORD_CODE_SUCCESS ("0024"),
	RESET_PASSWORD_ERROR_DESCRIPTION ("REQUEST PASSWORD IS NOT VALID OR EMPTY"),
	RESET_PASSWORD_EXCEPTION_CODE ("0025"),
	
	RESET_PASSWORD_DATA_OBJECT_ERROR_CODE ("0026"),
	RESET_PASSWORD_DATA_OBJECT_ERROR_MESSAGE ("RESET PASSWORD DATA OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	
	RESET_PASSWORD_EXPIRE_DATA_OBJECT_ERROR_CODE ("0026"),
	RESET_PASSWORD_EXPIRE_DATA_OBJECT_ERROR_MESSAGE ("RESET PASSWORD LINK HAS BEEN EXPIRED"),
	
	LOGIN_DATA_OBJECT_ERROR_CODE ("0027"),
	LOGIN_DATA_OBJECT_ERROR_MESSAGE ("LOGIN DATA OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	LOGIN_EMAIL_EMPTY_CODE_FAILD ("0028"),
	LOGIN_EMAIL_EMPTY_MESSAGE_FAILD ("EMAIL ADDRESS IS MANDATORY."),
	
	LOGIN_EMAIL_VALID_CODE_FAILD ("0029"),
	LOGIN_EMAIL_VALID_MESSAGE_FAILD ("Please enter a valid email address."),
	
	LOGIN_PASSWORD_EMPTY_CODE_FAILD ("0030"),
	LOGIN_PASSWORD_EMPTY_MESSAGE_FAILD ("PASSWORD IS MANDATORY."),
	
	LOGIN_USERNAME_CODE_FAILD ("0031"),
	LOGIN_USERNAME_MESSAGE_FAILD ("Either email id or password doesn't exist"),
	
	LOGIN_PASSWORD_CODE_FAILD ("0032"),
	LOGIN_PASSWORD_MESSAGE_FAILD ("Either email id or password doesn't exist"),
	
	LOGIN_USER_PASS_CODE_FAILD ("0033"),
	LOGIN_USER_PASS_MESSAGE_FAILD ("Either email id or password doesn't exist"),
	
	LOGIN_VERIFY_CODE_FAILD ("0034"),
	LOGIN_VERIFY_MESSAGE_FAILD ("USER NOT VERIFY."),
	
	LOGIN_CODE_SUCCESS ("0035"),
	LOGIN_MESSAGE_SUCCESS ("Login successful. Please wait while moving to desired page."),
	
	USER_CODE_FAILD ("0036"),
	USER_MESSAGE_FAILD ("USER DOESN'T EXIST "),
	
	USER_CODE_SUCCESS ("0037"),
	USER_MESSAGE_SUCCESS ("USER SUCCESS."),
	
	CAPTCHA_EMPTY_CODE_FAILD ("0038"),
	CAPTCHA_EMPTY_MESSAGE_FAILD ("CAPTCHA CODE IS MANDATORY."),
	
	STUDENT_CODE_FAILD ("0039"),
	STUDENT_MESSAGE_FAILD ("STUDENT DOESN'T EXIST "),
	
	PARENT_CODE_FAILD ("0040"),
	PARENT_MESSAGE_FAILD ("PARENT DOESN'T EXIST "),
	
	CAPTCHA_VALID_CODE_FAILD ("0041"),
	CAPTCHA_VALID_MESSAGE_FAILD ("Please enter valid captcha"),
	
	EMAIL_AVAILABLE_DELETE_CODE_FAILURE ("0042"),
	EMAIL_AVAILABLE_DELETE_MESSAGE_FAILIRE ("Your account is deactivated."),
	
	EMAIL_AVAILABLE_NOTENABLE_CODE_FAILURE ("0043"),
	EMAIL_AVAILABLE_NOTENABLE_MESSAGE_FAILIRE ("Your email address has not been verified yet."),
	
	EMAIL_AVAILABLE_ENABLE_CODE_FAILURE ("0044"),
	EMAIL_AVAILABLE_ENABLE_MESSAGE_FAILIRE ("VERIFY"),
	
	FORGOT_PASSWORD_INVALID_CODE_FAILURE ("0045"),
	FORGOT_PASSWORD_INVALID_MESSAGE_FAILURE ("PLEASE PROVIDE VALID EMAIL ADDRESS."),
	
	FORGOT_PASSWORD_EMPTY_CODE_FAILURE ("0046"),
	FORGOT_PASSWORD_EMPTY_MESSAGE_FAILURE ("PLEASE PROVIDE AN EMAIL ADDRESS."),
	
	FORGOT_PASSWORD_NOTREGISTER_CODE_FAILURE ("0047"),
	
	CONTACTUS_CODE_SUCCESS ("0048"),
	CONTACTUS_MESSAGE_SUCCESS ("Your request has been receivied and our representative contact you shortly. Thanks"),
	CONTACTUS_CODE_FAILURE ("0049"),
	CONTACTUS_MESSAGE_FAILURE ("Some of the mandatory fields are missing"),
	INQUIRY_REPLY_SUCCESS_CODE ("0050"),
	INQUIRY_REPLY_MESSAGE_SUCCESS ("Your Inquiry-reply has been sent to user. Thanks"),
	
	INQUIRY_REPLY_CODE_FAILURE ("0051"),
	INQUIRY_REPLY_MESSAGE_FAILURE ("Some problem occoured here, we know that and working on the same"),
	
	SIGNUP_TEACHER_DATA_OBJECT_ERROR_CODE ("0050"),
	SIGNUP_TEACHER_DATA_OBJECT_ERROR_MESSAGE ("SIGNUP TEACHER DATA OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	CONTACT_DATA_OBJECT_ERROR_CODE ("0051"),
	CONTACT_DATA_OBJECT_ERROR_MESSAGE ("CONTACT DATA OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	UPDATE_STUDENT_DATA_OBJECT_ERROR_CODE ("0052"),
	UPDATE_STUDENT_DATA_OBJECT_ERROR_MESSAGE ("UPDATE STUDENT PROFILE DATA OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	UPDATE_STUDENT_RESIDENT_DATA_OBJECT_ERROR_CODE ("0053"),
	UPDATE_STUDENT_RESIDENT_DATA_OBJECT_ERROR_MESSAGE ("UPDATE STUDENT PROFILE RESIDENT ADDRESS DATA OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	UPDATE_STUDENT_MAILING_DATA_OBJECT_ERROR_CODE ("0054"),
	UPDATE_STUDENT_MAILING_DATA_OBJECT_ERROR_MESSAGE ("UPDATE STUDENT PROFILE MAILING ADDRESS DATA OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	UPDATE_STUDENT_PARENT_DATA_OBJECT_ERROR_CODE ("0055"),
	UPDATE_STUDENT_PARENT_DATA_OBJECT_ERROR_MESSAGE ("UPDATE STUDENT PROFILE MAILING ADDRESS DATA OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	COUNTRY_STATE_DATA_OBJECT_ERROR_CODE ("0056"),
	COUNTRY_STATE_DATA_OBJECT_ERROR_MESSAGE ("PLEASE SELECT COUNTRY, STATE OR CITY"),
	
	BIRTHPLACE_DATA_OBJECT_ERROR_CODE ("0057"),
	BIRTHPLACE_DATA_OBJECT_ERROR_MESSAGE ("PLEASE FILL BIRTH PLACE"),
	
	NATIONALITY_DATA_OBJECT_ERROR_CODE ("0058"),
	NATIONALITY_DATA_OBJECT_ERROR_MESSAGE ("Nationality is required"),
	
	UPDATE_STUDENT_SUCCESS_CODE ("0059"),
	UPDATE_STUDENT_SUCCESS_MESSAGE ("PROFILE UPDATE SUCCESSFULLY"),
	
	SIGNUP_TEACHER_PROFILE_DATA_OBJECT_ERROR_CODE ("0060"),
	SIGNUP_TEACHER_PROFILE_DATA_OBJECT_ERROR_MESSAGE ("TEACHER PROFILE UPDATE OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	TEACHER_ACTION_APPROVE_SUCCESS_CODE ("0060"),
	TEACHER_ACTION_APPROVE_SUCCESS_MESSAGE ("Approved Successfully "),
	
	TEACHER_ACTION_DECLINE_SUCCESS_CODE ("0060"),
	TEACHER_ACTION_DECLINE_SUCCESS_MESSAGE ("Declined Successfully"),
	
	TEACHER_ACTION_APPROVE_AND_REDIRECT_TO_BANK_SUCCESS_CODE ("0062"),
	TEACHER_ACTION_APPROVE_AND_REDIRECT_TO_BANK_SUCCESS_MESSAGE ("Approved and Redirect to Bank Detail Successfully "),
	
	TEACHER_ACTION_QUALIFIED_SUCCESS_CODE ("0061"),
	TEACHER_ACTION_QUALIFIED_SUCCESS_MESSAGE ("Teacher Qualified Successfully"),
	
	TEACHER_ACTION_NON_QUALIFIED_SUCCESS_CODE ("0061"),
	TEACHER_ACTION_NON_QUALIFIED_SUCCESS_MESSAGE ("Disqualified Successfully"),
	
	TEACHER_INTERVIEW_QUALIFIED_SUCCESS_CODE ("0062"),
	TEACHER_INTERVIEW_QUALIFIED_SUCCESS_MESSAGE ("Teacher Interview Qualified Successfully"),
	
	TEACHER_INTERVIEW_NON_QUALIFIED_SUCCESS_CODE ("0062"),
	TEACHER_INTERVIEW_NON_QUALIFIED_SUCCESS_MESSAGE ("Teacher Interview Disqualified Successfully"),
	
	
	
	TASK_DATA_OBJECT_ERROR_CODE ("0061"),
	TASK_DATA_OBJECT_ERROR_MESSAGE ("TASK DATA OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	TASK_NOTFOUND_FAILED_CODE ("0062"),
	TASK_NOTFOUND_FAILED_MESSAGE ("TASK NOT FOUND"),
	
	TASK_SUBMIT_SUCCESS_CODE ("0063"),
	TASK_SUBMIT_SUCCESS_MESSAGE ("TASK SAVED SUCCESSFULLY"),
	
	RESET_OLDPASSWORD_CODE_SUCCESS ("0064"),
	RESET_OLDPASSWORD_ERROR_DESCRIPTION ("Old Password does not match"),
	
	TASK_INVALID_CODE ("0065"),
	TASK_INVALID_MESSAGE ("Task invalid, please send correct task"),
	
	CONTACTUS_DATA_OBJECT_ERROR_CODE ("0066"),
	CONTACTUS_DATA_OBJECT_ERROR_MESSAGE ("CONTACTUS DATA OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	ENQUIRY_REPLY_DATA_OBJECT_ERROR_MESSAGE ("ENQUIRYREPLY DATA OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	TEACHER_RATING_COMMENT_SUCCESS_CODE ("0067"),
	TEACHER_RATING_COMMENT_SUCCESS_MESSAGE ("Please fill comments"),
	
	TEACHER_RATING_SUCCESS_CODE ("0068"),
	TEACHER_RATING_SUCCESS_MESSAGE ("Please fill select one Rating"),
	
	TEACHER_RATING_SUBMIT_SUCCESS_CODE ("0069"),
	TEACHER_RATING_SUBMIT_SUCCESS_MESSAGE ("Successfully submit rating"),
	
	SET_NOTFOUND_FAILED_CODE ("0070"),
	SET_NOTFOUND_FAILED_MESSAGE ("QUESTION SET NOT FOUND"),
	
	QUESTION_NOTFOUND_FAILED_CODE ("0071"),
	QUESTION_NOTFOUND_FAILED_MESSAGE ("QUESTION ANSWER NOT FOUND"),
	
	SET_SUBMIT_SUCCESS_CODE ("0072"),
	SET_SUBMIT_SUCCESS_MESSAGE ("QUESTION SET SAVED SUCCESSFULLY"),
	
	QUESTION_SUBMIT_SUCCESS_CODE ("0073"),
	QUESTION_SUBMIT_SUCCESS_MESSAGE ("QUESTION ANSWER SAVED SUCCESSFULLY"),
	
	SCHOLAR_NOTFOUND_FAILED_CODE ("0074"),
	SCHOLAR_NOTFOUND_FAILED_MESSAGE ("SCHOLARSHIP CODE NOT FOUND"),
	
	SCHOLAR_SUBMIT_SUCCESS_CODE ("0075"),
	SCHOLAR_SUBMIT_SUCCESS_MESSAGE ("SCHOLARSHIP CODE SAVED SUCCESSFULLY"),

	SCHOLAR_ACTION_STATUS_SUCCESS_CODE ("0075A"),
	SCHOLAR_ACTION_STATUS_SUCCESS_MESSAGE ("SCHOLARSHIP CODE INACTIVE SUCCESSFULLY"),
	
	MEETING_NOTFOUND_FAILED_CODE ("0076"),
	MEETING_NOTFOUND_FAILED_MESSAGE ("MEETING NOT FOUND"),
	
	MEETING_SUBMIT_SUCCESS_CODE ("0077"),
	MEETING_SUBMIT_SUCCESS_MESSAGE ("MEETING SAVED SUCCESSFULLY"),
	
	MEETING_DATA_OBJECT_ERROR_CODE ("0078"),
	MEETING_DATA_OBJECT_ERROR_MESSAGE ("MEETING DATA OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	MEETING_ALREADY_EXIST_CODE ("93"),
	MEETING_ALREADY_EXIST_MESSAGE ("MEETING ALREADY EXISTS"),
	
	PTM_NOTFOUND_FAILED_CODE ("0079"),
	PTM_NOTFOUND_FAILED_MESSAGE ("PTM NOT FOUND"),
	
	PTM_SUBMIT_SUCCESS_CODE ("0080"),
	PTM_SUBMIT_SUCCESS_MESSAGE ("PTM MEETING SAVED SUCCESSFULLY"),
	
	PTM_DATA_OBJECT_ERROR_CODE ("0081"),
	PTM_DATA_OBJECT_ERROR_MESSAGE ("PTM DATA OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	EMAIL_NOTFOUND_FAILED_CODE ("0082"),
	EMAIL_NOTFOUND_FAILED_MESSAGE ("EMAIL NOT FOUND"),
	
	EMAIL_SUBMIT_SUCCESS_CODE ("0083"),
	EMAIL_SUBMIT_SUCCESS_MESSAGE ("EMAIL SENT SUCCESSFULLY"),
	
	EMAIL_DATA_OBJECT_ERROR_CODE ("0084"),
	EMAIL_DATA_OBJECT_ERROR_MESSAGE ("EMAIL DATA OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	MAPPING_NOTFOUND_FAILED_CODE ("0085"),
	MAPPING_NOTFOUND_FAILED_MESSAGE ("Record Not Found"),
	
	MAPPING_SUBMIT_SUCCESS_CODE ("0086"),
	MAPPING_SUBMIT_SUCCESS_MESSAGE ("Student Teacher Mapped Successfully"),
	
	MAPPING_DATA_OBJECT_ERROR_CODE ("0087"),
	MAPPING_DATA_OBJECT_ERROR_MESSAGE ("DATA OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	
	SIGNUP_SCHOOL_DATA_OBJECT_ERROR_CODE ("0088"),
	SIGNUP_SCHOOL_DATA_OBJECT_ERROR_MESSAGE ("SIGNUP SCHOOL DATA OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	SIGNUP_SCHOOL_PROFILE_DATA_OBJECT_ERROR_CODE ("0089"),
	SIGNUP_SCHOOL_PROFILE_DATA_OBJECT_ERROR_MESSAGE ("SIGNUP SCHOOL UPDATE PROFILE OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	SIGNUP_SCHOOL_REVIEW_AND_APPROVAL_OBJECT_ERROR_CODE ("0090"),
	SIGNUP_SCHOOL_REVIEW_AND_APPROVAL_OBJECT_ERROR_MESSAGE ("SIGNUP SCHOOL REVIEW AND APPROVAL OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	SIGNUP_SCHOOL_PAYMENT_STRUCTURE_OBJECT_ERROR_CODE ("0091"),
	SIGNUP_SCHOOL_PAYMENT_STRUCTURE_OBJECT_ERROR_MESSAGE ("SIGNUP SCHOOL PAYMENT STURCURE OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	SIGNUP_SCHOOL_SIGNING_CONTRACT_OBJECT_ERROR_CODE ("0092"),
	SIGNUP_SCHOOL_SIGNING_CONTRACT_OBJECT_ERROR_MESSAGE ("SIGNUP SCHOOL SIGNING CONTRACT OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	SLOT_NOTFOUND_FAILED_CODE ("0093"),
	SLOT_NOTFOUND_FAILED_MESSAGE ("SLOT NOT FOUND"),
	
	SLOT_SUBMIT_SUCCESS_CODE ("0094"),
	SLOT_SUBMIT_SUCCESS_MESSAGE ("SLOT SAVED SUCCESSFULLY"),
	
	VISIT_DATA_OBJECT_ERROR_CODE ("0095"),
	VISIT_DATA_OBJECT_ERROR_MESSAGE ("VISIT DATA OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	VISIT_DATE_NOTFOUND_FAILED_CODE ("0096"),
	VISIT_DATE_NOTFOUND_FAILED_MESSAGE ("VISIT DATE NOT FOUND"),
	
	VISIT_DATE_SUBMIT_SUCCESS_CODE ("0097"),
	VISIT_DATE_SUBMIT_SUCCESS_MESSAGE ("VISIT DATE SAVED SUCCESSFULLY"),
	
	VISIT_DATE_NOT_AVALILABLE_CODE ("0098"),
	VISIT_DATE_NOT_AVALILABLE_MESSAGE ("VISIT DATE NOT AVILABLE, PLEASE CHOOSE ANOTHER DATE"),
	
	TRAVEL_DETAIL_SUBMIT_SUCCESS_CODE ("0099"),
	TRAVEL_DETAIL_SUBMIT_SUCCESS_MESSAGE ("TRAVEL DETAIL SAVED SUCCESSFULLY"),
	
	EVALUATION_DETAIL_SUBMIT_SUCCESS_CODE ("0100"),
	EVALUATION_DETAIL_SAVE_SUCCESS_MESSAGE ("EVALUATION DETAIL SAVED SUCCESSFULLY"),
	EVALUATION_DETAIL_SUBMIT_SUCCESS_MESSAGE ("EVALUATION DETAIL SUBMITTED SUCCESSFULLY"),
	
	EVALUATION_REMARKS_SUBMIT_SUCCESS_CODE ("0101"),
	EVALUATION_REMARKS_SAVE_SUCCESS_MESSAGE ("EVALUATION REMARKS SAVE SUCCESSFULLY"),
	EVALUATION_REMARKS_SUBMIT_SUCCESS_MESSAGE ("EVALUATION REMARKS SUBMITTED SUCCESSFULLY"),
	EVALUATION_REMARKS_STATUS_SUCCESS_MESSAGE ("EVALUATION REMARKS STATUS UPDATED SUCCESSFULLY"),
	
	COUNSELOR_SUBMIT_SUCCESS_CODE ("000108"),
	COUNSELOR_SUBMIT_SUCCESS_MESSAGE ("COUNSELOR SAVED SUCCESSFULLY"),
	ADD_COUNSELOR_DATA_OBJECT_ERROR_MESSAGE ("ADD COUNSELOR DATA OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	COUNSELOR_FOUND_FAILED_MESSAGE ("COUNSELOR NOT FOUND"),
	COUNSELOR_SEND_SUCCESS_MESSAGE ("New Password with Referral Code send successfully"),
	
	REFERRAL_NOTFOUND_FAILED_CODE ("00740"),
	REFERRAL_NOTFOUND_FAILED_MESSAGE ("REFERRAL CODE NOT FOUND"),
	
	REFERRAL_SUBMIT_SUCCESS_CODE ("00750"),
	REFERRAL_SUBMIT_SUCCESS_MESSAGE ("REFERRAL CODE SAVED SUCCESSFULLY"),
	
	STUDENT_LMS_USER_SUCCESS_CODE("0101"),
	STUDENT_LMS_USER_SUCCESS_MESSAGE("LMS USER CREATED SUCCESSFULLY"),
	STUDENT_LMS_USER_ERROR_CODE("0102"),
	STUDENT_LMS_USER_ERROR_MESSAGE("LMS USER ALREADY EXIST"),
	
	STUDENT_SESSION_SUCCESS_CODE("0107"),
	STUDENT_SESSION_SUCCESS_MESSAGE("STUDENT SESSION CREATED SUCCESSFULLY"),
	STUDENT_SESSION_ERROR_CODE("0108"),
	STUDENT_SESSION_ERROR_MESSAGE("STUDENT SESSION EXIST"),
	
	REQUEST_DEMO_MESSAGE_SUCCESS ("Your request has been receivied and our representative contact you shortly. Thanks"),
	REQUEST_DEMO_CODE_SUCCESS ("0103"),
	REQUEST_DEMO_INVALID_REQUESTID_SUCCESS ("Requested demo is not available please contact adminstrator"),
	REQUEST_DEMO_CODE_ERROR ("0104"),
	RAISE_DEMO_REQUEST_ERROR_CODE("0105"),
	RAISE_REQUEST_DEMO_MESSAGE_SUCCESS ("Mail sent successfully"),
	LMS_STUDENT_PERFORMANCE_ERROR_CODE("0106"),
	LMS_STUDENT_PERFORMANCE_SUCCESS ("Student status saved successfully"),
	
	TEACHER_DATA_OBJECT_ERROR_CODE ("0107"),
	TEACHER_DATA_OBJECT_ERROR_MESSAGE ("TEACHER DATA OBJECT IS NOT AVAILABLE IN REQUEST BODY"),
	
	MODULE_INVALID_CODE ("P101"),
	MODULE_INVALID_MESSAGE ("Module invalid, please send correct info"),
	
	MODULE_SUCCESS_CODE ("P102"),
	MODULE_SUCCESS_MESSAGE ("Module save Success"),
	
	ROLE_SUCCESS_CODE ("P102"),
	ROLE_SUCCESS_MESSAGE ("Role save Success"),
	
	ROLE_INVALID_CODE ("P101"),
	ROLE_INVALID_MESSAGE ("Role invalid, please send correct info"),
	
	ROLERIGHTS_INVALID_CODE ("P101"),
	ROLERIGHTS_INVALID_MESSAGE ("Role invalid, please send correct info"),
	
	ROLERIGHTS_SUCCESS_CODE ("P102"),
	ROLERIGHTS_SUCCESS_MESSAGE ("Success"),
	
	
	
	
	
	
	
	STUDENT_NAME_MESSAGE_FAILURE ("Student Name is required"),
	
	
	USER_REGISTRATION_STAGE_SAVE_PASSWORD_DETAILS (9),
	USER_REGISTRATION_STAGE_SAVE_USER_DETAILS (10),
	
	USER_REGISTRATION_STAGE_SAVE_STUDENT_DETAILS (11),
	USER_REGISTRATION_STAGE_SAVE_PARENTS_DETAILS (12),
	USER_REGISTRATION_STAGE_SAVE_STUDENT_ADDRESS_DETAILS (13),
	USER_REGISTRATION_STAGE_SAVE_STUDENT_COURSE_DETAILS (14),
	USER_REGISTRATION_STAGE_SAVE_STUDENT_REVIEW_DETAILS (15),
	
	USER_FLEX_REGISTRATION_STAGE_SAVE_STUDENT_COURSE_DETAILS (10),
	USER_FLEX_REGISTRATION_STAGE_SAVE_STUDENT_DETAILS (11),
	USER_FLEX_REGISTRATION_STAGE_SAVE_STUDENT_PREVIOUS_QUALIFICATION (12),
	USER_FLEX_REGISTRATION_STAGE_SAVE_STUDENT_PAYMENT_OPTION (13),
	USER_FLEX_REGISTRATION_STAGE_SAVE_STUDENT_REVIEW_DETAILS (14),
	
	
	USER_REGISTRATION_STAGE_SAVE_TEACHER_BASIC_DETAILS (11),
	USER_REGISTRATION_STAGE_SAVE_TEACHER_UPDATE_PROFILE_DETAILS (12),
	USER_REGISTRATION_STAGE_SAVE_TEACHER_REVIEW_DETAILS (13),
	USER_REGISTRATION_STAGE_SAVE_TEACHER_PROFILE_APPROVED_BY_ADMIN (14),
	USER_REGISTRATION_STAGE_SAVE_TEACHER_PROFILE_DECLINED_BY_ADMIN (15),
	USER_REGISTRATION_STAGE_SAVE_TEACHER_TRAINING_QUESTIONS_SUBMITTED(16),
	USER_REGISTRATION_STAGE_APPROVE_TEACHER_TRAINING_DETAILS_BY_ADMIN (17),
	USER_REGISTRATION_STAGE_DECLINED_TEACHER_TRAINING_DETAILS_BY_ADMIN (18),
	USER_REGISTRATION_STAGE_SAVE_TEACHER_INTERVIEW_DETAILS (19),
	USER_REGISTRATION_STAGE_INTERVIEW_QUALIFIED_TEACHER_BY_ADMIN (20),
	USER_REGISTRATION_STAGE_INTERVIEW_DISQUALIFIED_TEACHER_BY_ADMIN (21),
	USER_REGISTRATION_STAGE_REDIRECT_TO_BANK_TEACHER_BY_ADMIN (22),
	
	USER_REGISTRATION_STAGE_SAVE_SCHOOL_BASIC_DETAILS (11),
	USER_REGISTRATION_STAGE_SAVE_SCHOOL_UPDATE_PROFILE_DETAILS (12),
	USER_REGISTRATION_STAGE_SAVE_SCHOOL_REVIEW_DETAILS (13),
	USER_REGISTRATION_STAGE_SAVE_SCHOOL_APPROVED (14),
	USER_REGISTRATION_STAGE_SAVE_SCHOOL_DECLINED (15),
	USER_REGISTRATION_STAGE_SAVE_SCHOOL_PAYMENT_STRUCTURE (16),
	USER_REGISTRATION_STAGE_SAVE_SCHOOL_SIGNING_CONTRAT (17),
	USER_REGISTRATION_STAGE_SAVE_SCHOOL_PAY_WIRE_TRANSFER (18),
	USER_REGISTRATION_STAGE_SAVE_SCHOOL_PAY_WIRE_TRANSFER_DECLINE (19),
	
	
	SCHOOL_B2B_PROCESS_STAGE_DATE_OF_VISIT(1),
	SCHOOL_B2B_PROCESS_STAGE_DATE_OF_VISIT_APROVED_BY_ADMIN(2),
	SCHOOL_B2B_PROCESS_STAGE_DATE_OF_VISIT_DECLINED_BY_ADMIN(3),
//	SCHOOL_B2B_PROCESS_STAGE_DATE_OF_VISIT_ASSIGNED_RM(4),
//	SCHOOL_B2B_PROCESS_STAGE_DATE_OF_VISIT_TRAVEL_DETAIL_RM(5),
	SCHOOL_B2B_PROCESS_STAGE_EVALUATION_FORM_SAVED(6),
	SCHOOL_B2B_PROCESS_STAGE_EVALUATION_FORM_SUBMITTED(7),
	SCHOOL_B2B_PROCESS_STAGE_EVALUATION_REMARKS_SAVED_BY_AUDITOR(8),
	SCHOOL_B2B_PROCESS_STAGE_EVALUATION_REMARKS_SUBMITTED_BY_AUDITOR(9),
	
	SCHOOL_B2B_PROCESS_STAGE_EVALUATION_REMARKS_STATUS__REJECTED_BY_AUDITOR(10),
	SCHOOL_B2B_PROCESS_STAGE_EVALUATION_REMARKS_STATUS_ONHOLD_BY_AUDITOR(11),
	SCHOOL_B2B_PROCESS_STAGE_EVALUATION_REMARKS_STATUS_APPROVED_BY_AUDITOR(12),
	
	SCHOOL_B2B_PROCESS_STAGE_EVALUATION_REPORT_DECLINED_BY_ADMIN(13),
	SCHOOL_B2B_PROCESS_STAGE_EVALUATION_REPORT_PUBLISHED_BY_ADMIN(14),
	SCHOOL_B2B_PROCESS_STAGE_PARTNERSHIP_FEE_SUBMITTED(15),
	SCHOOL_B2B_PROCESS_STAGE_PARTNERSHIP_FEE_BY_WIRE_TRANSFER_SUBMITTED_(16),
	SCHOOL_B2B_PROCESS_STAGE_PARTNERSHIP_FEE_BY_WIRE_TRANSFER_DECLINED(17),
	SCHOOL_B2B_PROCESS_STAGE_PARTNERSHIP_FEE_BY_WIRE_TRANSFER_APPROVED_(18),
	SCHOOL_B2B_PROCESS_STAGE_STUDENT_FEE_BY_WIRE_TRANSFER_SUBMITTED_(19),
	SCHOOL_B2B_PROCESS_STAGE_STUDENT_FEE_BY_WIRE_TRANSFER_APPROVED_(20),
	SCHOOL_B2B_PROCESS_STAGE_ANNUAL_FEE_BY_WIRE_TRANSFER_SUBMITTED_(21),
	SCHOOL_B2B_PROCESS_STAGE_ANNUAL_FEE_BY_WIRE_TRANSFER_APPROVED_(22),
	SCHOOL_B2B_PROCESS_STAGE_ANNUAL_FEE_BY_WIRE_TRANSFER_DECLINED(23),
	
	
	USER_REGISTRATION_COMPLETED (0),
	USER_REGISTRATION_WITHDRAWN (1),
	
	SUCCESS_CODE("100"),
	FAILD_CODE("101"),
	REQUEST_ERROR_CODE ("0000"),
	REQUEST_SUCCESS_CODE ("1111"),
	
	USER_TYPE_STUDENT ("STUDENT"),
	USER_TYPE_PARENT ("PARENT"),
	USER_TYPE_TEACHER ("TEACHER"),
	USER_TYPE_SCHOOL ("SCHOOL"),
	USER_TYPE_SCHOOL_B2B ("SCHOOL-B2B"),
	USER_TYPE_AUDITOR ("AUDITOR"),
	USER_TYPE_COUNSELOR ("COUNSELOR"),
	USER_TYPE_COMMON ("COMMON"),
	
	JSON  ("JSON"),
	SORT_DIRECTION  ("asc"),
	SECRET_KEY  ("ABCDEFGHIJKLMNOP"),
	SERI_ADMIN_EXCEPTION  ("1001"),
	PICKR_ACTIVE  ("Y"),
	PICKR_DELETED  ("N"),
	BASE_DTO  ("baseDTO"),
	
	LOG_ENTERING  ("******Entering******"),
	LOG_EXITING  ("******Exiting******"),
	NO_ERROR  ("NO ERROR FOUND !!!."),
	UNSUCCESSFUL_MSG  ("FAILURE !!!."),
	BAD_REQUEST  ("Request Not Valid.Please Correct Your Request Format !!!."),
	SERI_EXCEPTION_CODE ("1000"),
	ACTIVE  ("Y"),
	DELETED  ("N"),
	PROCESS_INITIATED  ("Process Initiated."),
	DASHBOARD_CRON_SCHEDULAR  ("Schedular Updated The Dashboard Data Sucessfully.Please Check The Database."),
	ADMIN_LOGIN_SUCCESS  ("Login Successfully."),
	ADMIN_LOGOUT_SUCCESS  ("Logout successfully from session."),
	ADMIN_REGISTRATION_SUCCESS  ("Admin User Registration Successfully."),
	ADMIN_REGISTRATION_FAILURE  ("Admin User Registration Failed !!!."),
	ADMIN_INVALID_LOGIN  ("Invalid Login Details !!!."),
	ADMIN_INVALID_LOGIN_ID  ("Please Enter Valid Login Id !!!."),
	ADMIN_INVALID_EMAIL_ID  ("Please Enter Valid Email Id !!!."),
	ADMIN_INVALID_ROLE  ("Please Select Valid Role !!!."),
	ADMIN_INVALID_PWD  ("Please Enter Valid Password !!!."),
	ADMIN_INVALID_MOBILE_NO  ("Please Enter Valid Mobile Number !!!."),
	ADMIN_INVALID_DOB  ("Please Enter Valid Date Of Birth !!!."),
	ADMIN_INVALID_GENDER  ("Please Enter Valid Gender !!!."),
	ADMIN_INVALID_FLAG  ("Please Enter Valid Flag Status !!!."),
	ADMIN_INVALID_USER_FIRST_NAME  ("Please Enter Valid First User Name !!!."),
	ADMIN_INVALID_USER_LAST_NAME  ("Please Enter Valid User Last Name !!!."),
	LANDING_PAGE_NOT_FOUND  ("Landing Page Not Found."),
	INVALID_ENTITY_TO_DTO_CONVERSION  ("Entity To DTO Conversion Failure!!!."),
	COUNTRY_MAPPING_NOT_FOUND  ("Countries Mapping Not Found."),
	CURRENCY_MAPPING_NOT_FOUND  ("Currency Mapping Not Found."),
	REQUESTED_COUNTRY_NOT_SAVE  ("Requested Country Is Not Saved ."),
	REQUESTED_COUNTRY_NOT_UPDATED  ("Requested Country Not Updated."),
	REQUESTED_COUNTRY_NOT_FOUND ("Country Not Found."),
	ALL_FIELD_REQUIRED  ("All fields are required ."),
	INVALID_COUNTRY_KEY_FOUND  ("Country  Key Is Not Valid .Please Enter valid Country Key.!!!"),
	COUNTRY_ADDED_SUCCESS  ("Country Added SuccessFully ."),
	COUNTRY_ALREADY_EXIST  ("Country Already Exist With Same Country Code ."),
	COUNTRY_EDITED_SUCCESS  ("Country Edited SuccessFully ."),
	COUNTRY_ACTIVATE_SUCCESS  ("Country Acivated SuccessFully ."),
	COUNTRY_DEACTIVATE_SUCCESS  ("Country De-Acivated SuccessFully ."),
	COUNTRY_NOT_FOUND  ("Country Not Found.Please Select Valid Country !!!"),
	COUNTRY_LIST_FOUND  ("Country list found Successfully."),
	COUNTRY_FOUND_SUCCESS  ("Country Found Successfully ."),
	REQUESTED_CURRENCY_NOT_SAVE  ("Requested Currency Is Not Saved ."),
	REQUESTED_CURRENCY_NOT_REMOVE  ("Requested Currency Not Removed."),
	REQUESTED_CURRENCY_NOT_UPDATED  ("Requested Currency Not Updated."),
	REQUESTED_CURRENCY_NOT_FOUND  ("Currency Not Found."),
	REQUESTED_BANK_NOT_FOUND  ("Bank Not Found."),
	BANK_ALREADY_EXISTS  ("Bank Already Exist With Same Name ."),
	BANK_ADDED_SUCCESS  ("Bank Added SuccessFully ."),
	BANK_EDITED_SUCCESS  ("Bank Edited SuccessFully ."),
	REQUESTED_BANK_NOT_UPDATED  ("Requested Bank Not Updated."),
	INVALID_BANK_KEY_FOUND  ("Bank Key Is Not Valid .Please Enter valid Bank Key!!!"),
	BANK_DEACTIVATED_SUCCESS  ("Bank De-Acivated SuccessFully ."),
	BANK_ACTIVATED_SUCCESS  ("Bank Acitivated SuccessFully ."),
	CURRENCY_ADDED_SUCCESS  ("Currency Added SuccessFully ."),
	INVALID_CURRENCY_KEY_FOUND  ("Currency Key Is Not Valid .Please Enter valid Currency Key!!!"),
	CURRENCY_ALREADY_EXIST  ("Currency Already Exist With Same Currency Code ."),
	CURRENCY_EDITED_SUCCESS  ("Currency Edited SuccessFully ."),
	CURRENCY_DETAILS_SUCCESS ("Country Found Successfully ."),
	CURRENCY_ACTIVATE_SUCCESS  ("Currency Acivated SuccessFully ."),
	CURRENCY_DEACTIVATE_SUCCESS  ("Currency De-Acivated SuccessFully ."),
	CURRENCY_NOT_FOUND  ("Currency Not Found.Please Select Valid Currency !!!"),
	CURRENCY_LIST_FOUND  ("Currency list found Successfully."),
	ROLE_ADDED_SUCCESS  ("Role Added SuccessFully ."),
	FIND_ROLE_PERMISSION_SUCCESS  ("Role Permission Found SuccessFully "),
	ROLE_ALREADY_EXISTS  ("Role Already Exist With Same Name ."),
	ROLE_EDITED_SUCCESS  ("Role Edited SuccessFully ."),
	REQUESTED_ROLE_NOT_FOUND  ("User Role Not Found."),
	PARTICULAR_ROLE_DETAILS_SUCCESS  ("Particular Role details get successfully ."),
	ROLE_ACTIVATED_SUCCESS  ("Role Acivated SuccessFully ."),
	ROLE_DEACTIVATED_SUCCESS  ("Role De-Acivated SuccessFully ."),
	ROLE_NOT_FOUND  ("Role Not Found.Please Enter Valid Role !!!"),
	INVALID_ROLE_KEY_FOUND  ("User Role Key Is Not Valid .Please Enter valid Role Key!!!"),
	GET_PARTICULAR_ADMIN_SUCCESS  ("Get Particular Admin Successfully ."),
	GET_USER_ROLE_SUCCESS  ("User Role Data Get Successfully ."),
	SECURITY_QUESTION_DEACTIVATED_SUCCESS  ("Security Question De-Acivated SuccessFully ."),
	SECURITY_QUESTION_ACTIVATED_SUCCESS  ("Security Question Acitivated SuccessFully ."),
	USER_MASTER_DEACTIVATED_SUCCESS  ("User  De-Acivated SuccessFully ."),
	USER_MASTER_ACTIVATED_SUCCESS  ("User Acitivated SuccessFully ."),
	ADMIN_USER_ACTIVATED_SUCCESS  ("Admin User Acitivated SuccessFully ."),
	ADMIN_USER_DEACTIVATED_SUCCESS  ("Admin User De-Acivated SuccessFully ."),
	REQUESTED_ADMIN_USER_NOT_UPDATED  ("Requested User Not Updated."),
	DO_NOT_MODIFY_VALUE  ("Please do not modify value."),
	ADMIN_USER_EDITED_SUCCESS  ("Admin User Edited SuccessFully ."),
	INVALID_ADMIN_USER_ID  ("Admin User  Id Is Not Valid .Please Enter valid Id !!!"),
	GET_USER_DATA_SUCCESS  ("Admin User Data Get Successfully ."),
	ADMIN_USER_LIST_FOUND  ("Admin User List Found Successfully."),
	ADMIN_USER_NOT_FOUND  ("Admin User Not Found."),
	ADMIN_USER_ALREADY_EXIST  ("Admin User Already Exist In Our Record."),
	ADMIN_INVALID_USER_STATUS  ("Admin User Have Not Valid Registraion Status !!!."),
	FILE_NAME  ("attachment"),
	TEMPLATE_LOCATION  ("email-template/"),
	READ_PERMISSION  ("Read"),
	WRITE_PERMISSION  ("Write"),
	BOTH_PERMISSION  ("Both"),
	COMP_SUBJECT_LIST_BY_GRADE_KEY("COMP-SUBJECT-LIST-BY-GRADE"),
	OPTIONAL_SUBJECT_LIST_BY_GRADE_KEY("OPTIONAL-SUBJECT-LIST-BY-GRADE"),
	GET_CURRENT_SUBJECT_MARKS_BY_SUBJECT_ID("GET_CURRENT_SUBJECT_MARKS_BY_SUBJECT_ID"),
	COURSE_LIST_BY_STANDARD_ID("COURSE-LIST-BY-STANDARD-ID"),

	DASHBOARD_HOD_COUNT_ICON  ("&#xe016;"),
	DASHBOARD_HOD_COUNT_COLOR  ("danger"),
	
	DASHBOARD_TEACHER_COUNT_ICON  ("&#xe01b;"),
	DASHBOARD_TEACHER_COUNT_COLOR  ("megna"),
	
	DASHBOARD_STUDENT_COUNT_ICON  ("&#xe01b;"),
	DASHBOARD_STUDENT_COUNT_COLOR  ("primary"),
	
	DASHBOARD_PARENT_COUNT_ICON  ("&#xe00b;"),
	DASHBOARD_PARENT_COUNT_COLOR  ("success"),
	
	DASHBOARD_DEFAULT_COUNT_ICON  ("&#xe00b;"),
	DASHBOARD_DEFAULT_COUNT_COLOR  ("danger"),
	
	BASE_CURRENCY_USD  ("USD"),
	BASE_CURRENCY_AUD  ("AUD"),
	BASE_CURRENCY_GBP  ("GBP"),
	BASE_CURRENCY_CAD  ("CAD"),
	BASE_CURRENCY_EUR  ("EUR"),
	BASE_CURRENCY_NZD  ("NZD"),
	BASE_CURRENCY_INR  ("INR"),
	BASE_CURRENCY_BDT  ("BDT"),

	PERSONAL_USER  ("Personal"),
	BUSINESS_USER  ("Business"),

	ADMIN_INVALID_CHANGE_PASS_LINK  ("Change password link is not valid.Please click on valid link"),

	// activity log for mobile
	MOBILE_ACTIVITY_LOG  (2),
	LOGIN_PROCESS  (22),
	ACCOUNT_SUMMARY  (25),
	MANAGE_CARDS  (76),
	MANAGE_BANK_ACCOUNT  (77),
	CURRENCY_CONVERSION  (78),
	CURRENCY_CONVERSION_CALCULATION  (79),
	REMOVE_CARD_DETAILS  (80),
	SET_PRIMARY_ACCOUNT  (81),
	USER_PROFILE_DETAILS  (82),
	SEND_LINK_FORGOT_PASSWORD_EMAIL_VERIFICATION  (83),
	EMAIL_VERIFICATION  (84),
	NOTIFICATION_DETAILS  (85),
	YOUR_PAY_CREDENTIAL_REQUEST  (92),
	YOURPAY_MOBILE_TRANSACTION  (93),
	MODIFY_NOTIFICATION  (86),

	// activity log for web
	WEB_ACTIVITY_LOG  (1),
	UPDATE_PROFILE_IMAGE  (37),
	UPDATE_COMPANY_LOGO  (38),
	SEARCH_USER_FOR_SEND_PAYMENT  (59),
	SEARCH_USER_FOR_RECEIVE_PAYMENT  (60),
	SEARCH_USER_FOR_CREATE_INVOICE  (61),
	SEND_PAYMENT_TAB  (26),
	REQUEST_PAYMENT_TAB  (27),
	CREATE_INVOICE_TAB  (30),
	PAYMENT_INITIATED  (62),
	PAYMENT_TRANSFER_SUCCESSFULLY  (63),
	PAYMENT_TRANSFER_UNSUCCESSFULL  (64),
	EDIT_INVOICE  (57),
	INVOICE_SEND  (55),
	PREVIEW_INVOICE  (54),
	MANAGE_INVOICE_TAB  (31),
	SEARCH_INVOICE_DATA  (58),
	PREVIEW_INVOICE_SEND  (56),
	RIGHT_SIDE_SEARCH_DATA_ON_DASHBOARD  (68),
	LEFT_SIDE_SEARCH_DATA_ON_DASHBOARD  (69),
	DASHBOARD_TAB  (24),
	PAYMENT_METHOD_TAB  (29),
	PAYOUT_WITHDRAW_TAB  (28),
	BANK_WITHDRAW_PROCESS  (47),
	ADD_BANK_ACCOUNT  (44),
	ADD_BANK_ACCOUNT_PROCESS  (48),
	ADD_CREDIT_CARD  (42),
	ADD_DEBIT_CARD  (43),
	ADD_CARD_PROCESS  (49),
	LOGOUT  (46),
	ACCOUNT_LOCKED  (70),
	INVALID_LOGIN_PASSWORD  (71),
	USER_SETTINGS  (32),
	USER_NAME_CHANGE  (33),
	UPDATE_EMAIL_ID  (35),
	UPDATE_MOBILE_NO  (36),
	ADDRESS_CHANGE  (34),
	UPDATE_USER_LOGIN_PASSWORD  (39),
	UPDATE_USER_TXN_PASSWORD  (40),
	FORGOT_PASSWORD_EMAIL_VERIFICATION  (65),
	FORGOT_PASSWORD_OTP_VERIFICATION  (66),
	RESET_PASSWORD_SUCCESSFULLY  (67),
	SEND_EMAIL_VERIFY_LINK  (50),
	SEND_OTP_TO_VERIFY_MOBILE  (51),
	MOBILE_VERIFIED_BY_OTP  (52),
	REFER_CLIENT  (53),

	PAY_YEARLY ("annually"),
	PAY_THEE_MONTH ("threeMonthly"),
	PAY_SIX_MONTH ("sixMonthInstall"),
	PAY_NINE_MONTH ("nineMonthInstall"),
	PAY_REGISTRATION ("registration"),
	PAY_BOOKSESSION ("bookSession"),
	PAY_HYBRID ("hybrid"),
	
	//File Attachments
	PROFILE_IMAGE(1),
	
	//teacher Attachments
	docCertificate(2),
	docExperience(3),
	docCV(4),
	
	//school Attachments
	docAffiliationCertificate(5),
	docAssociationCertificate(6),
	docSchoolLicenceCertificate(7),
	docFrontViewImage(8),
	docPrincipalRoomImage(9),
	docStaffRoomImage(10),
	docClassroomRommImage(11),
	docComputerLabImage(12),
	docPlaygroundImage(13),
	docLibraryImage(14),
	
	//student Attachments
	docAgeProof(14),
	docAddressProof(15),
	docSignatureProof(16),
	docLastAcadmicProof(17),
	docTravelProof(18),
	
	
	//schoolB2B Attachments
	docPhotoProof(19),
	docBirthProof(20),
	docStudentAddressProof(21),
	docImmunizationProof(22),
	docAcademicProof(23),
	SCHOOL_SIGNED_CONTRACT_PDF_ATTACHMENT_TYPE(24),
	EVALUATION_PDF_ATTACHMENT_TYPE(25),
	doctravelDetail(26),
	paymentAnnualAttachment(27),
	paymentPartnershipAttachment(28),
	paymentStudentFeeAttachment(29),
	paymentOneTimeApplicationFee(30),
	
	REGISTRATION_SUBJECT_FEE_TITLE ("REGISTRATION_SUBJECT_FEE"),
	REGISTRATION_FEE_TITLE ("REGISTRATION_FEE"),
	SUBJECT_FEE_TITLE ("Student Subject Fee"),
	SUBJECT_FEE ("SUBJECT_FEE"),
	BOOKSESSION_FEE_TITLE ("BOOKSESSION_FEE"),
	
	INATALLMENT_FEE ("INSTALLMENT-FEE"),
	INATALLMENT_THREE_MONTH_TITLE ("Student Subject Fee"),
	INATALLMENT_SIX_TITLE ("Student Subject Fee"),
	INATALLMENT_NINE_TITLE ("Student Subject Fee"),
	INATALLMENT_ONE_TIME_TITLE ("Student Subject Fee"),
	
	SCHOOL_APPLICATION_FEE_TITLE("One Time Application Fee"),
	SCHOOL_APPLICATION_FEE_TYPE("One_time_Application_Fee"),
	
	SCHOOL_PROSPECTIVE_PARTERNERSHIP_FEE("On-site Prospective-Partnership visit Fee"),
	
	SCHOOL_PARTERNERSHIP_FEE_TITLE("One-time Partnership Fee"),
	SCHOOL_PARTERNERSHIP_FEE_TYPE("One_time_Partnership_Fee"),
	//SCHOOL_PARTERNERSHIP_FEE_AMOUNT(5000),
	SCHOOL_ANNUAL_FEE_TITLE("School Annual Dues"),
	SCHOOL_ANNUAL_FEE_TYPE("Annual_Dues"),
	
	
	WIRE_TRANSFER_NUMBER("WIRE-TRANSFER-NUMBER"),
	SCHOOL_VISIT_DATE_FINE_FEE_TITLE("SCHOOL VISIT DATE FINE FEE"),
	SCHOOL_VISIT_DATE_FINE_FEE_TYPE("SCHOOL_VISIT_DATE_FINE_FEE"),
	//SCHOOL_VISIT_DATE_FINE_FEE(100),
	//SCHOOL_B2B_APPLICATION_FEE(1000),
	SCHOOL_STUDENT_FEE_TITLE("SCHOOL STUDENT FEE"),
	SCHOOL_STUDENT_FEE_TYPE("SCHOOL-STUDENT-FEE"),
	//SCHOOL_STUDENT_FEE_AMOUNT(100),
	
	TEACHER_REQUEST_FEE_HALF_CREDIT("TEACHER_REQUEST_FEE_HALF_CREDIT"),
	TEACHER_REQUEST_FEE_FULL_CREDIT("TEACHER_REQUEST_FEE_FULL_CREDIT"),
	TEACHER_REQUEST_FEE_TITLE("TEACHER REQUEST FEE"),
	TEACHER_REQUEST_TITLE("TEACHER_REQUEST_TITLE"),
	
	SIGN_TYPE_OFFLINE ("Offline"),
	SIGN_TYPE_ONLINE ("Online"),
	SIGN_TYPE_ONLINE_FLEX ("Online-Flex"),
	SIGN_TYPE_ONLINE_VOCATIONAL ("Online-Vocational"),
	TOTAL_MONTH(12),
	
	KEY_MEMBERS_ID(1),
	KEY_ACADEMIC_STAFF_ID(2),
	KEY_NON_ACADEMIC_STAFF_ID(3),
	KEY_IT_SUPPORT_STAFF_ID(4),
	KEY_MANAGING_CENTER_ID(5),
	
	TOTAL_DAYS_FOR_EVALUATION(20),
	
	PAYMENT_TRANSFER_TYPE_ONLINE(0),
	PAYMENT_TRANSFER_TYPE_WIRE_TRANSFER(1),
	
	TEACHER_ACCOUNT_DETAILS_BANK_ACCOUNT ("BANK_ACCOUNT"),
	TEACHER_ACCOUNT_DETAILS_PAYPAL ("PAYPAL"),
	
	
	ADD_TIPS("ADD-TIPS"),
	UPDATE_TIPS_STATUS("UPDATE_TIPS_STATUS"),
	TEACHERS_COMPLETED_NOT_FOUND_MESSAGE("EMAIL CAN'T BE SEND BECAUSE NO ANY COMPLETED TEACHER FOUNDS "),
	ALLOWED_ENGLISH_KEYBOARD_ONLY("Please use the English Keyboard while providing information"),
	VENDOR_ID("e0a569bd-eaeb-4811-8594-ff9d41a3b945"),
	
	EVENT_ID_SIGNUP("716a563e-299b-4200-936c-c06ab24d87b3"),
	EVENT_ID_TRANSCRIPT_PUBLISHED("83325041-5cdc-4220-af92-f3b107fc449a"),
	EVENT_ID_BOOK_SESSION_STUDENT("83325041-5cdc-4220-af92-f3b107fc449a"),
	EVENT_ID_TEACHER_FEEDBACK("83325041-5cdc-4220-af92-f3b107fc449a"),
	EVENT_ID_BOOK_SESSION_TEACHER("83325041-5cdc-4220-af92-f3b107fc449a"),
	;
	
	private Integer activityValue;
	private String value;

	private SeriConstant(final String value){
		this.value = value;
	}
	private SeriConstant(final Integer activityValue){
		this.activityValue = activityValue;
	}

	public Integer getactivityValue() {
		return activityValue;
	}
	public String getValue() {
		return value;
	}
}
